### ISSUE TITLE
Clarify validation of OAuth URIs

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#101]
The `authorizationUri` is not mandatory when only the `client_credentials` authorizationGrant is supported.

**Comment by aldonline** [comment]
Will be clarified in the RAML 1.0 spec ( cc @blakeembrey )

**Comment by sichvoge** [comment]
It seems, according to some other sources like Ping, that the `authorizationUri` is only mandatory when using either `authorization_code` or `implicit` grant types. For any other it is not mandatory.
