### ISSUE TITLE
Date formats

### ISSUE THREAD

**Issue by dmartinezg** [raml-org/raml-spec#105]
Modify the types in named parameters, to add the following types:

Type|Description
----|-----------
`iso-date`|A date encoded as defined in ISO 8601
`iso-time`|A time encoded as defined in ISO 8601
`iso-datetime`|A combined date and time encoded as defined in ISO 8601

**Comment by DWvanGeest** [comment]
+1

An API description spec shouldn't limit me to using only one data/time format in my API. I would argue you should add some kind of custom/other type where the API builder can specify a different format.

**Comment by usarid** [comment]
Tentatively deferring this to a future version of RAML

**Comment by mj1856** [comment]
:+1:  Also, consider that date+time is valuable both with and without offset, for different purposes. Try to align with XSD in this area.

**Comment by benhamill** [comment]
Because this is still open, it looks like this is already addressed in RAML 1.0rc2: https://github.com/raml-org/raml-spec/blob/raml-10-rc2/versions/raml-10/raml-10.md#date

I'm not, actually, sure what the state of that branch and document are. Is the 1.0 spec linked from raml.org done? Does that mean the `raml-10-rc2` is actually about a future release (1.1? 2.0?)? Is 1.0 still in a candidacy state? Is there a better place for me to get answers to questions like this?

**Comment by sichvoge** [comment]
@benhamill, really sorry about the late response. You might find the information highlighted in our Wiki [here](https://github.com/raml-org/raml-spec/wiki/RAML-1.0-RC2---Plan) quite informative. It basically explains the current branching structure that we use moving to RAML 1.0 GA. In summary, RAML 1.0 has been published with its first release candidate RC1, or RAML 1.0 RC1, in November. That version is reflected inside the `raml-10` branch. In the time till now, we worked with the community to improve certain aspects of RC1 and are about to release RC2. That version is inside `raml-10-rc2`.

Let me know if there is anything else.

**Comment by sichvoge** [comment]
I'll mark that issue as `invalid` since it will be covered by the RAML 1.0 RC2 changes described [here](https://github.com/raml-org/raml-spec/issues/202#issuecomment-192126058).

**Comment by benhamill** [comment]
@sichvoge: Thanks. It might be good to make it more clear on raml.org that the 1.0 spec isn't the _real_ 1.0 spec, but a release candidate (just labeling the link on the website as "1.0rc1" is probably enough). Or, if it's actually 1.0, then maybe rc2 is actually the WIP of RAML 1.1?

**Comment by sichvoge** [comment]
I agree that the labels might be a bit confusing! What you get is really just 1.0, there is not yet a 1.1 version.
