### ISSUE TITLE
Add `.ext` alias for `mediaTypeExtension`

### ISSUE THREAD

**Issue by aldonline** [raml-org/raml-spec#121]
Problems with current state of the art:

1.  `mediaTypeExtension` is long
  * This yields **noisy and verbose RAML** files for APIs that use this feature extensively - this affects API developers. ( see [twitter.raml](https://raw.githubusercontent.com/mulesoft/api-console/master/dist/examples/twitter.raml) )
  * Its verbosity **pollutes any generated documentation** - this affects API consumers
2. It's **usage is unintuitive with respect to the dot** - this affects API developers

To illustrate (2). Which of the following is correct?
`/foo/bar{mediaTypeExtension}`
or
`/foo/bar.{mediaTypeExtension}`
 ( Note that the second one has a dot )

The answer is that the first one is correct as per the spec. The dot is part of the value.
This is not hard to understand but it did make me stop and think during my first few days with RAML and I can extrapolate to other developers.

**Proposal: Insert an alias: `.ext`**

So this:
`/foo/bar{mediaTypeExtension}`
Can be safely replaced by this:
`/foo/bar{.ext}`

Rationale:

* Short - RAML sources and docs will benefit from this
* Intuitive ( IMHO ) - It is not hard to understand what it means even if you've never seen it before. I can't say the same thing about mediaTypeExtension ( I argue that getting your head around it does require you to read the spec at least once )
* The dot as part of the parameter name is an explicit reminder that it should be part of the value ( so you won't feel tempted to add it on the outer path as well )
* The dot as part of the name should significantly lower the probability of collisions with parameters used in existing 0.8 APIs

**Comment by sichvoge** [comment]
Done in RAML 1.0 RC1 #181
