### ISSUE TITLE
Arrays in a schema.

### ISSUE THREAD

**Issue by k-funk** [raml-org/raml-spec#122]
The docs/tutorial don't mention how to write up a schema that includes an array.

I've found this on SO, but I think it should be mentioned more explicitly in the tutorial/docs if this is valid:
```
...
        "email": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "emailid": {
                        "type": "string",
                        "required": true
                    }
                }
            }
        },
...
```
source: [stackoverflow: 26702642](http://stackoverflow.com/a/26702642/1707152)

Furthermore, the [spec](http://raml.org/spec.html#type) leads me to believe that primitives are the only "type" I should use.

**Comment by sichvoge** [comment]
More related to JSON schema than RAML. Closing it.
