### ISSUE TITLE
Is documentation Markdown or not

### ISSUE THREAD

**Issue by dmartinezg** [raml-org/raml-spec#13]
The spec says that "the description property MAY be formatted using Markdown". 

We've noticed (with the instagram RAML) that a description might have markdown embedded in it by mistake:

```
description: |
        … the user_has_liked key which ...
```

which results in italics via Markdown.

We should discuss having a single format for documentation, either markdown, plaintext or some other format.

**Comment by geewrites** [comment]
To avoid religious wars, I advocate including in the RAML 1.0 spec a formal way to identify the markdown specification the API prefers. Some prefer Github-flavored Makdown, others prefer Vim-flavored Markdown, and still others can't live without CommonMark. 

If it is necessary to choose just one, I hope CommonMark will be seriously considered. When combined with the Markdown DITA plugin, CommonMark can be consumed by the DITA Open Toolkit. through which Markdown can be transformed into a variety of delivery formats.

**Comment by sichvoge** [comment]
Thats being introduced in RAML 1.0.
