### ISSUE TITLE
Allow ability to refer to specific types inside schema

### ISSUE THREAD

**Issue by justjacksonn** [raml-org/raml-spec#138]
Unless I am missing how to do this, there doesn't seem to be a way, at least with xml schema, to specify the defined type in a schema for a given schema: tag for any body. For example, we have a schema with several types defined inside.. and some xsd's include other xsd's in the same namespace. When designing my resources, I want to specify that a given resource or sub-resource returns (or accepts) a specific type within the xsd. Something like !include path-to-xsd/file.xsd#definedType to pin point a specific type in the xsd to use. This would be good for the upcoming 1.0 additions of multiple examples as well.

**Comment by sichvoge** [comment]
Thats a duplicate for https://github.com/raml-org/raml-spec/issues/170. Let's keep track of this in there.
