### ISSUE TITLE
General purpose way to combine several RAML files into one

### ISSUE THREAD

**Issue by justjacksonn** [raml-org/raml-spec#140]
Not sure if this is possible, but it would be great to have a top level RAML doc that can include several other RAML docs, but override their top level description, version, etc.. so as to allow multiple smaller projects with APIs be combined into one big company (or top level project) API. This is mostly for the purpose of generating a single document from multiple RAML files. In particular I am thinking of the raml2html project, but things like Java raml parser being able to load multiple RAML files, schemas, etc and allow parsing as if it were all one RAML file, would be very  helpful in creating a sort of uber API.

This would also be helpful for things like generating SDKs. Assuming the SDK generator was equipped to generate say a zip file of the SDK generated output, being able to offer an SDK that spans multiple smaller projects that work in conjunction with one another would potentially be better or easier to provide to consumers than multiple smaller SDKs (as well as individual docs for said API/SDKs).

If there is a way to include and/or combine multiple RAML files, I've not seen it documented elsewhere.

**Comment by sichvoge** [comment]
Let's have the discussion on #146 and close that one if you don't mind. If yes, please feel free to open it again.
