### ISSUE TITLE
include external responses into a method response

### ISSUE THREAD

**Issue by rdeoliv** [raml-org/raml-spec#145]
Hi there, so here is the usecase:

Some of my responses (400 and 401) are always the same and wanted to reuse them instead of copying/pasting those two into my resources.
I created a file error.raml containing 

`400:
  body:
    application/json:
      example: |
        {
          "success": false,
          "message": "Bad request - The server cannot process the request due to a client error"
        }
401:
  body:
    application/json:
      example: |
        {
          "success": false,
          "message": "Bad request 2 - The server cannot process the request due to a client error"
        }`

When it comes to reuse:

This works:
`/user:
  delete:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "success":true,
                  "message": "Account deleted"
              }`

This works:
`/user:
  delete:
    responses:
      !include error.raml`

This does not:
`/user:
  delete:
    responses:
      !include error.raml
      200:
        body:
          application/json:
            example: |
              {
                  "success":true,
                  "message": "Account deleted"
              }`

Neither this:
`/user:
  delete:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "success":true,
                  "message": "Account deleted"
              }
      !include error.raml`

Is it intended?
At the moment we are using resourceType as it's probably be the best alternative for this.

**Comment by blakeembrey** [comment]
@rdeoliv I think the best (current) solution is to use traits or resource types.

```yaml
#%RAML 0.8
title: Example API
traits:
  - error400: !include error.raml
/user:
  delete:
    is: [error400]
    responses:
      200:
        body:
          application/json:
            example: |
              { "success":true, "message": "Account deleted" }
```

However, in the future there is a proposal for using the YAML merge syntax which would result in something much clearer and similar to the functionality you are trying to use (https://github.com/raml-org/raml-spec/issues/103).

**Comment by justjacksonn** [comment]
Is this feature coming in the 1.0.. the ability to include at different locations that are currently not supported in 0.8?

**Comment by Klotair** [comment]
Hi,

Did someone tried to generalize error codes as traits ? 

the following seems to be invalid for the raml console:
```yaml
#%RAML 0.8
title: Example API
traits:
  - error400: 
      400:
        description: "Bad Request"
        body:
          application/json:
            schema: ServerError
/user:
  delete:
    is: [error400]
    responses:
      200:
        body:
          application/json:
            example: |
              { "success":true, "message": "Account deleted" }
```

The raml api console give me the following error:
```
(line 5) - property: '400' is invalid in a trait
```

Am I missing something ?
Thanks

**Comment by dmartinezg** [comment]
Hi @Klotair, a trait has the same properties as a method, so you would need to do something like:

```
#%RAML 0.8
title: Example API
traits:
  - error400:
      responses:
        400:
          description: "Bad Request"
          body:
            application/json:
              schema: ServerError
/user:
  delete:
    is: [error400]
    responses:
      200:
        body:
          application/json:
            example: |
              { "success":true, "message": "Account deleted" }
```

**Comment by Klotair** [comment]
Quick answer!
Thanks, it works better
