### ISSUE TITLE
providing a new level of "metadata" for APIs to support API search engines or repositories

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#147]
I am currently researching how RAML can enable search engines or repositories (like MuleSoft's Anypoint Exchange) to index RAML based APIs so that consumer can easier find and discover them.

To provide this level of discoverability, the spec needs to be extended to provide necessary information for the tools. To start with, the following is a list of my personal preferences:

Property Name | Property Type | Description
-------------------- | ------------------- | ---------------
tags | String Array | contains a list of tags associated to the API defined by RAML
description | Map | A YAML map representing two different child properties to give further information about the API. <p><ul><li>`short` - brief overview about the API (string - required)</li><li>`long` - a more detailed description of the API (string - required)</li></ul></p>
createdBy | Map | A YAML map representing information about the API creator. <p><ul><li>`name` - full name of the creator (string - required)</li><li>`email` - contact email adress (string - required)</li><li>`x-link-?` - additional information, eg `x-link-twitter`, `x-link-facebook`, `x-link-blog`, etc. (URL - optional)</li></ul></p>
createdOn | Date | contains the date when the API was created
lastUpdate | Date | contains the date when the API was last updated (<b>needs to be clarified if that means the interface or implementation of an API</b>)
logo | URL | this is based on the following issue #127 
raml-version | String | indicating what RAML spec version has been used

An example:

```raml
#%RAML 0.8
title: My API
baseUri: http://localhost:8081/api

tags: [ api, test, in that example ]
description:
  short: this is a test api
  long: in this test api you can do bla bla
createdBy:
  name: John Doe
  email: john.doe@example.com
  x-link-twitter: https://twitter.com/JohnDoe_
createdOn: 2015-04-13
lastUpdated: 2015-04-16
logo: http://example.com/logo.png
raml-version: 0.8
```

All the mentioned root properties should be optional. I also thought if it makes sense to place all under a root property to make it easier for tools to check if you specified these kind of meta information or not. 

What does everyone think? Do we need any additional information?

**Comment by dmartinezg** [comment]
Version is already provided at the top of a RAML file, what is the point of repeating it?

**Comment by dmartinezg** [comment]
I don't think that contact information should be required fields (or any of the other fields for that matter)

Also, what is the requiredness of the top-level properties themselves?

A field must be required iif leaving it out leaves you with a non-working or non-understandable API, none of these look like they fit the bill correctly, as _none_ of them are crucial to the semantics of the API themselves.

I could even argue, that all of these should/could be fitted into the global "metadata" requirement discussed here https://github.com/raml-org/raml-spec/issues/110 . I wonder if RAML should be in the business of defining non-semantic/non-functional metadata fields (although it is perfectly fine if any tool requires the existence of a specific set of fields).

**Comment by sichvoge** [comment]
Hi @dmartinezg,

thanks a lot for your comments.

indeed - the version is in the beginning of a RAML file, but there is no parser storing it to be retrieved by tools? BTW, just to clarify, I don't mean the version of your API, instead the version of the spec used (0.8, 1.0, etc).

In terms of the required or empty fields. That should not happen. What I meant with optional is that you can define tags or not. Basically the RAMLs below are both valid:

```raml
version: 1.0
title: API Test

tags: [ hello, test ]
```

```raml
version: 1.0
title: API Test
```

I am not really sure if metadata is really what I was looking for as those are very open how you name them. There is no standardisation behind it. Adding it to the specification would give the possibility to have that. We should make RAML easier to be discovered and how that is done, or how RAML provides the information for such a process should be standardised. I don't think the metadata get's us there, but happy to hear other comments as well.

**Comment by justjacksonn** [comment]
@sichvoge are you saying that the metadata should NOT be in RAML 1.0. or that these particular attributes you are inquiring about are in addition to? I'd say metadata is a necessary part of the 1.0 spec in order to support (and especially for) raml-generator and the likes. It will allow for those that wish to use raml-generator or any of the parsers provided, to have their own custom API tags that hey can document and build their own parsers for. If that is not what you are saying than I apologize for the rant. :)

**Comment by sichvoge** [comment]
No, metadata IS an essential part and should be added to the spec. Fully agree! What I am saying is that the spec should contain fixed property to give more context what's your API is about. That can be used throughout various tools.

**Comment by justjacksonn** [comment]
I am not opposed to some "standardized" properties, but I'd still argue that the open ended metadata is a necessity as well, such that anyone can define specific meta "key" names, and then parse for them. This is especially useful for a company that may have different products/teams, but want consistent APIs/SDKs/Docs.. they would define some meta elements that their parser writer would then utilize for specific purposes, such as adding meta info for each language generator they wish to support to try to generate language specific features. Another company may add in some proprietary needs that only make sense in the realm of their own business. Those are things you can't pre-define and enforce as part of the RAML spec. 

The alternative is to add some "meta" property option to every element in RAML now, and have it be some json string that would then need to be parsed by the consuming tool and converted in whatever way they would need. I'd rather have the ability to have any number of meta tags with values and parse for those, then having to look for a specific defined property "meta" and then take it's value, parse it's value into an object or something, then use the value(s).

**Comment by sichvoge** [comment]
As I said - this is not replacing the "metadata" feature. That will be still somehow going into the spec, but the discussion around it should go into the dedicated issue. :)

**Comment by justjacksonn** [comment]
Oh..my apologies.. I thought the conversation was around making these
defined instead of having the open ended meta feature.

**Comment by apimatic** [comment]
We would love to support this metadata in our discovery website as well as github widget for SDK generation. Checkout the links to see what I mean: https://sdks.io   and  https://github.com/apimatic/videos

**Comment by sichvoge** [comment]
@apimatic wouldn't it be cool if you can also define the languages you support and you discover it inside the RAML, and on sdks.io you present it to consumer and you add the language

**Comment by sichvoge** [comment]
That can be achieved with annotations introduced in RAML 1.0 RC1 #174
