### ISSUE TITLE
ISO 8601 for date/time representation

### ISSUE THREAD

**Issue by Racum** [raml-org/raml-spec#15]
What about add an option to define dates as [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601)?

This format is still very human-readable, and it is better supported by all the languages, including native support in JavaScript:

```javascript
date1 = new Date();
iso8601Str = date1.toJSON();  // "2013-10-31T12:35:36.864Z"
date2 = new Date(iso8601Str);
date1.toString() === date2.toString()  // true
```

I agree with XKCD about this subject:

![XKCD 1179](http://imgs.xkcd.com/comics/iso_8601.png)

[Original XKCD 1179](http://xkcd.com/1179/).

[]'s
Racum

**Comment by artdudin** [comment]
+1

**Comment by sichvoge** [comment]
@saurabhnanda - You can define that using RAML's DataTypes.

**Comment by sichvoge** [comment]
Guys please comment to #202

**Comment by mj1856** [comment]
:+1:, and see my comments on #202.
