### ISSUE TITLE
Wrong regular expression for Default Media Type

### ISSUE THREAD

**Issue by ddossot** [raml-org/raml-spec#153]
In https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#default-media-type the spec states:

> A custom type that conforms to the regular expression, "application\/[A-Za-z.-0-1]*+?(json|xml)"

I see numerous issues here:
- `/` doesn't need escaping,
- `.` and `-` should be escaped in the range,
- the `0-1` range is wrong: it should be `0-9`
- the `+` should be escaped.

The following fixes these problems: `application/[A-Za-z\.\-0-9]*\+?(json|xml)`

**Comment by econchick** [comment]
Definitely filed something similar with #133

**Comment by ddossot** [comment]
I swear I searched for similar issues... my search-fu is so weak :crying_cat_face: 

Closing as dup of #133
