### ISSUE TITLE
raml tutorial required usage doesn't follow JSON schema

### ISSUE THREAD

**Issue by bpytlik** [raml-org/raml-spec#159]
The schema in [this example](http://raml.org/docs-200.html#extract-schemas) shows `required` set to `true`. According to [this link](http://json-schema.org/latest/json-schema-validation.html#anchor61) `required` must be an array of strings. The items in the array are the names of the properties that must be in the object.

**Comment by dmartinezg** [comment]
You sent the link to DRAFT-4 of JSON Schema, while RAML specifically targets DRAFT-3.

Changing the syntax of the `required` keyword is precisely one of the changes between both versions.
