### ISSUE TITLE
Documentation generation without RAML API

### ISSUE THREAD

**Issue by fmielke** [raml-org/raml-spec#161]
Hi guys, 

sorry, but I didn't find out anything about this topic. So, we have an own written REST API and want to generate only the documentation (not an API) with RAML. Is this possible?  

Thank you!  Kind regards, Fabian

**Comment by nohorbee** [comment]
Sure!
Take a look to this 2 projects:
- https://github.com/mulesoft/api-console
- https://github.com/kevinrenskers/raml2html

Or this one, if you are like me and prefer MarkDown instead of HTML: 
https://github.com/kevinrenskers/raml2md

**Comment by irgalieri** [comment]
+1 @nohorbee.

@fmielke: if you want convert to pdf https://github.com/our-bts/raml2pdf

**Comment by fmielke** [comment]
Thank you!

**Comment by fmielke** [comment]
Okay, I am confused now. Maybe I didn't explain my isse in a right way.

Our own written REST API is not created with RAML, but rather with own Java code. So, is the RAML console able to use it as "stand-alone" and integrate it into an existing not RAML REST API?

**Comment by nohorbee** [comment]
Not that I know. RAML Console knows how to show the API RAML spec in a way that you don't need to read RAML. Additionally, it provides Mocking execution out of the box.

However, I used to work on a project that allowed you to go from RAML to JAX-RS and JAX-RS to RAML (code generation both ways). If you are using JAX-RS in Java, you should be able to automatically generate the RAML spec and use the console with it. Here is a link to this project: https://github.com/mulesoft/raml-for-jax-rs

**Comment by fmielke** [comment]
Great, @nohorbee !

**Comment by fmielke** [comment]
Hello again, 

is there a conversion from spring mvc, too?

**Comment by sichvoge** [comment]
There is a conversation on that in our forum http://forums.raml.org/t/raml-to-springmvc/735/18.
