### ISSUE TITLE
{version} as uri parameter

### ISSUE THREAD

**Issue by evangelina** [raml-org/raml-spec#163]
Hi,

What is the expected behavior of defining a **uri parameter** named *version* according to the spec? Going over the specification I found the following: 

On the *Base URI parameters* section:

> The special baseUriParameter version is reserved; processing applications MUST replace occurrences of {version} in any baseUri property values with the value of the root-level version property. The {version} parameter, if used in a baseUri, is required: if it is used in a baseUri, the version root-level property MUST be provided and MUST be a valid non-empty URI fragment.

On the *Base URI and baseUriParameters* section:

> If the baseUri value is a Level 1 Template URI, the following reserved base URI parameters are available for replacement:

>
URI Parameter | Value
-------------------- | -----------------
version|The content of the version field.

And finally, on the *Uri Parameters* section:

> The uriParameters CANNOT contain a key named version because it is a reserved URI parameter name

I don't quite understand what the expected behavior is, and that leaves me with three possibilities:

1) When version is used as a uriParameter, the parser implementation will behave as with the baseUriParameters and replace it with the RAML version.

2) It is not allowed to define a uriParameter named version and the parser implementation will fail.

3) It's a bug in the spec and a version uriParameter is allowed and the value is not replaced with the RAML version, it should behave as a regular uriParameter.

Thanks in advance for any clarification, 
Eva

**Comment by nohorbee** [comment]
It seems like if this old issue is still around.

When you use the uriParameter "version" it should be automatically replaced with the API version. I used to use it directly at the baseURI attribute, like this: ```baseUri: http://api.ramljukebox.io/{version}``` and the result is that all the URLs to invoke the API must include the version (ex: http://api.ramljukebox.io/2.0.0/.......).

Having said that, it's a reserved URI parameter (which doesn't mean you can't use it, but it has a special behavior), so, if you use it at the "resource level" it will behave the same way than if you use it at the baseUri property (it will be replaced with the version). For example:
```
/{version}:
  description: Duality on version
  get:
    description: which is the version
```

I guess that the idea was to provide flexibility to users trying to implement API versioning.

Please, take a look to this example: https://anypoint.mulesoft.com/apiplatform/nohorbee/#/portals/organizations/0f56f146-8f66-4eb5-872d-86d5e75115a6/apis/844/versions/739/pages/658

It contains a duality produced by using the version at both, baseURI property and resource level. In both cases, it's replaced.

I hope you find it clarifying.

**Comment by evangelina** [comment]
Thank you for clarifying Norberto! The parsers are not doing that, they only replace the {version} with the RAML root version when it's declared as baseUri. APIKit does replace it, but only under certain circumstances. 
So if this is the expected behavior, I will go ahead and file a ticket in the Java and Javascript parsers and in APIKit as well :)

Thank you!
