### ISSUE TITLE
Unified type system for data modeling

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#167]
Use a single type system for URI and query parameters, headers, and bodies.

It must be very easy to model the majority of data needs, but there should be plenty of reserve power for more sophisticated modeling:
- A spectrum of scalar, array, object, and union types;
- Optional properties, additional and patterned properties, scalar type specialization and enumeration, type expressions, and several less common type constraints

**Comment by sichvoge** [comment]
Can be closed. Done.
