### ISSUE TITLE
Wrap JSON and XML Schema

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#169]
Support embedding XML Schema and JSON Schema in new type system.

**Comment by braco** [comment]
Did this get lost in the 1.0 release?

**Comment by sichvoge** [comment]
It did not get lost ;) As RAML 1.0 is in a release candidate stage, some of these features are still under discussions with the community. This particular though will not be in 1.0, but is still in discussion for 1x. We will soon release a blog post that will explain some of these decision. Keep updated ;)
