### ISSUE TITLE
Annotations and Annotation Types

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#174]
Allow for adding "annotations", i.e. arbitrary metadata, to most places in the RAML tree.

Let these annotations be typed via reusable annotation types. This will enable entire new families of extensions: testing tools, implementation hooks,

**Comment by oberlies** [comment]
Is the annotation types specification formation already final? IMHO the way the `parameters` property was designed is sub-optimal: https://github.com/raml-org/raml-spec/issues/196

**Comment by sichvoge** [comment]
The Spec is currently in RC. and from what I have seen your suggestion would make sense. Anyone else has comments on that? There is an example of what @oberlies suggest in #196

**Comment by usarid** [comment]
See comments there - we can probably quickly agree on that solution and close this once the spec and implementation are updated accordingly.
