### ISSUE TITLE
Complete Support for OAuth Security Schemes

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#177]
Address #57 #99 #100 #101 #102

**Comment by sichvoge** [comment]
**Update**

Issue #99 is done.
Issue #102 is done.

**Comment by sichvoge** [comment]
**Update**

Issue #57 is closed as invalid. See [this comment](https://github.com/raml-org/raml-spec/issues/57#issuecomment-216011837).
Issue #100 is done.
