### ISSUE TITLE
New Type System Obviates Header Name Wildcards

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#182]
With the RAML 1.0 type system allowing additional and patterned properties, there is no longer a need for the special construct that allowed arbitrary additional header names (e.g. `X-Metadata-{*}`), so eliminate it.

**Comment by sichvoge** [comment]
Looking into RC1, I haven't seen that at all. @usarid can you please elaborate?!

**Comment by usarid** [comment]
```raml
headers:
  Age: integer
  /^X-Metadata-/: string
```
