### ISSUE TITLE
Override Rules

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#184]
Certain behaviors were not explicit in RAML 0.8; this fixes them. This includes:
* Peer resources that resolve to the same path, e.g. `/users` with a sub-resource `/{id}`, alongside `/users/{id}`
* Peer resources with similar URI parameters, e.g. `/{pictureId}` and `/{videoId}`
* Duplicate methods on a resource
* Multiple occurrences of the same media type in a response
* The order in which to apply multiple traits (and now types, since there is multiple inheritance)

There are a few others to clarify too.

**Comment by sichvoge** [comment]
Can you clarify a little bit more what you want to fix?

**Comment by sichvoge** [comment]
This is related to #199 I guess.

**Comment by usarid** [comment]
Yes, we need to probably bring back the overrides section, per #199 

Specifically to the points I raised in this current issue:
* Peer resources that resolve to the same path, e.g. `/users` with a sub-resource `/{id}`, alongside `/users/{id}` -- to be addressed in the overrides section
* Peer resources with similar URI parameters, e.g. `/{pictureId}` and `/{videoId}` -- ALLOWED, to be addressed in the overrides section
* Duplicate methods on a resource -- can not happen as it would be inconsistent YAML (because of duplication of properties)
* Multiple occurrences of the same media type in a response -- can not happen as it would be inconsistent YAML (because of duplication of properties)
* The order in which to apply multiple traits (and now types, since there is multiple inheritance) -- from left to right, but this too should be described explicitly in the section explaining how to apply traits and resource types, and in the section on multiple extensions (inheritance) of types.

**Comment by sichvoge** [comment]
> Peer resources that resolve to the same path, e.g. /users with a sub-resource /{id}, alongside /users/{id} -- to be addressed in the overrides section

@usarid - what is the default behaviour? I remember discussions about "marking" them as ambiguous and maybe add a warning in IDEs or so.

**Comment by sichvoge** [comment]
And also what about overloading definition that has been declared in traits and resource types?

**Comment by sichvoge** [comment]
Added a PR that introduces the new overloading section. @usarid can you please check and add any comments you might have. I know we discussed briefly that we might also not allow any  overloading of resources, for example:

```yaml
/users:
  /foo:
/users/foo
```

but allow things like:

```yaml
/users/{userId}:
/users/{username}:
/users/me:
```

The chapter at least gives us a base for discussion.

**Comment by svacas** [comment]
in case of ambiguity we should pick the first route that matches and validates all uri parameters?

**Comment by usarid** [comment]
Regarding overloading, @channel , I'm thinking of the following radical proposal: to completely forbid them when they're clearly ambiguous (i.e. to forbid them whenever the fully-combined path, which you get from combining the resource's path with all of its parents, is identical to another fully-combined path, WITHOUT consideration to the possible values of any URI parameters), and to always allow them otherwise. Does that mean that in some cases servers won't be able to disambiguate resources? Yes, but I don't know that we can prevent that in general anyways, and I don't think it's worth trying to allow certain cases that could clearly be, because they are corner cases.

Let me illustrate. This would be FORBIDDEN
```raml
/users:
  /foo:
/users/foo
```
(both paths combine to the same `/users/foo`), and this would ALWAYS be ALLOWED
```raml
/users/{userId}:
/users/{username}:
/users/me:
```
and it's up to implementations to sort out whether in fact the paths can be disambiguated in reality.

You might have said: wait, I need to allow some overloading so that I can describe with different data types the `GET`ting of `/users?admin=true` and of `/users?admin=false` but I would say you already can't describe that in YAML:
```raml
/users:
  queryParameters:
    admin:
      type: boolean
      enum: [ true ]
/users:
  queryParameters:
    admin:
      type: boolean
      enum: [ false ]
```
because the `/users` keys already conflict. So yes, there are *some* cases where you could describe overloaded resources in YAML and find a way to use overloading, but those seem random enough to me that we might as well go with something MUCH simpler, and live with the fact that some situations will need describing by a combination of union types and some text for humans to consume (this is unavoidable anyways).

**Comment by svacas** [comment]
will be part of the spec the rules for matching ambiguous routes or is it up to each tool to decide?

**Comment by usarid** [comment]
The spec would simply indicate that multiple fully-resolved paths that are identical (up to character encoding) are forbidden, and otherwise they are permitted, without specifying how processors should route HTTP requests.

**Comment by petrochenko-pavel-a** [comment]
I am almost agree, but I still would like to see some better support for use case with admin
`GET ting of /users?admin=true and of /users?admin=false`

You may  say that this can be supported with union types but in this case you will not be able to provide separate schemas for responses depending from value of `admin` parameter (of course you can use union type but you will not be able to represent dependency)

According to my experience this is important use case for representing some legacy APIs correctly.

**Comment by usarid** [comment]
An equally common case would be `/users/{userId}` where some values of `userId` return admin-level data while others do not, or even more properly, some values of the auth headers allow returning admin-level information about the user, and again wouldn't be capturable in an overloading section because the knowledge of which users or tokens should return different payloads is statefully determined by the server, vs being statically declarable. You might end up using some custom annotations:

```raml
responses:
  200:
    body:
      properties:
        name:
        facebookProfile:
          (admin):
        points:
          (admin):
```
but the client cannot know definitively when they'll get admin-level data back -- they just have to be prepared for it, in particular when they've submitted a `userId` or token they believe should return such data.

**Comment by sichvoge** [comment]
OK; closing that as invalid (since there is no need for specific overriding rules) and continue on #367.
