### ISSUE TITLE
Suggestion: Addition of the Capitalize Function to the raml spec

### ISSUE THREAD

**Issue by Lenois** [raml-org/raml-spec#185]
Pluralize and Singularize are useful. It would be helpful if a Capitalize Function were added to the spec as well. JsonSchema2POJO supports it, so I am able to generate my model classes correctly, but the documentation generators do not currently support it.

Would it be possible to get this in for 1.0?

**Comment by sichvoge** [comment]
@Lenois, that is also defined in #188. Therefore, I am closing this one.
