### ISSUE TITLE
Add more parameter functions to !singularize and !pluralize

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#188]
To allow greater matching possibilities in RAML 1 API specs, the following should be added to the list of string functions to be supported in RAML 1.

`!uppercase`: userId --> USERID
`!lowercase`: userId --> userid
`!lowercamelcase`: userId --> userId
`!uppercamelcase`: userId --> UserId
`!lowerunderscorecase`: userId --> user_id
`!upperunderscorecase`: userId --> USER_ID
`!lowerhyphencase`: userId --> user-id
`!upperhyphencase`: userId --> USER-ID

This is necessary when you use resource type and trait parameters that combine models, where the naming convention may be upper camel case (e.g. `Users`, `ProcessedInvoices`), with resources, where the naming convention for relative URI paths may be lower camel case (e.g. `users`, `processedInvoices`) or lower hyphen case (e.g. processed-invoices).

As with the other functions, the only locale supported is United States English.

**Comment by usarid** [comment]
For reference:

https://code.google.com/p/guava-libraries/source/browse/guava/src/com/google/common/base/CaseFormat.java?r=4fc7c376154e26f694eead7bc6720cfe6a06653a

**Comment by Lenois** [comment]
Awesome.

**Comment by sichvoge** [comment]
This is already part of the spec. So closing it.
