### ISSUE TITLE
Reuse of code in schemas and examples

### ISSUE THREAD

**Issue by DataGreed** [raml-org/raml-spec#189]
I've got a lot of resource examples that can be reused, but it seems that RAML does not support it.

Example:

```
/songs:
  /get:
    responses:
      200:
        body:
          application/json:
            example: |
              songs: [
                  {
                  "title": "Yesterday",
                  "artist": {
                     "name": "The Beatles",
                     "is_band": true
                   }
              ]

/artists:
  /get:
    responses:
      200:
        body:
          application/json:
            example: |
              artists: [
                  {
                    "name": "The Beatles",
                    "is_band": true
                  }
              ]    
```

As you see, Artist Dictionary is repeated in both resources in examples. Is there any way I can write it only once, so if I add a new field to the artist, I won't need to add it in all resources?

**Comment by sichvoge** [comment]
Hi @DataGreed, that is coming with the new type system in RAML 1.0 -> #168.

**Comment by DataGreed** [comment]
@sichvoge thank you for the answer. I've checked that out, but couldn't understand how exactly that would help with my example. I believe #168 is about defining json schema as yaml, not about inclusion of bits of text into examples

**Comment by sichvoge** [comment]
Something valid in RAML 1.0 should be:

```yaml
#%RAML 1.0
title: New API
version: v1
baseUri: http://api.samplehost.com

types:
  Artist:
    type: object
    properties:
      name:
        type: string
        example: "The Beatles"
      is_band:
        type: boolean
        example: true
  Song:
    type: object
    properties:
      title:
        type: string
        example: "Yesterday"
      artist: Artist
  Artists: Artist[]
  Songs: Song[]

/songs:
  get:
    responses:
      200:
        body:
          application/json: Songs
/artists:
  get:
    responses:
      200:
        body:
          application/json: Artists
```

As you can see you define the examples inside your type and therefore not replicating that into multiple different places. You also re-use the definition of your "schema". Hope that helps you to get an idea what we are working on. Let me know if you have any comments.

**Comment by DataGreed** [comment]
@sichvoge oh, I see now! Thanks, that's actually a pretty good idea to combine schema and example

**Comment by DataGreed** [comment]
@sichvoge BTW, is there any planned release date on 1.0?

**Comment by sichvoge** [comment]
The planned release for the spec is somewhere next week afaik

**Comment by sichvoge** [comment]
Guess that is resolved - closing it.
