### ISSUE TITLE
Example contains description in invalid place

### ISSUE THREAD

**Issue by greenrd** [raml-org/raml-spec#191]
The following example in the RAML 0.8 spec does not seem to be valid - `ramlcop` and `raml-tester` both reject the description inside the body, and such a construction is not documented anywhere in the spec.

```
/media/{mediaid}/content:
  displayName: Content
  get:
    description: |
      Get a media file.
    responses:
      200:
        body:
          "*/*":
            description: |
                Returns the media file.
```

**Comment by sichvoge** [comment]
Hi @greenrd, thanks for reporting that - we are currently work on the documentation aligned to the RAML 1.0 release. That will be fixed.
