### ISSUE TITLE
Can we add links to the sections that talks about a specific property

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#194]
There are quite some tables in the spec that gives a high level view on the spec. Additionally to that, some properties have a separated section that gives more information. Currently I need to scroll to find these section, but I would like to be able to go there by clicking a link maybe inside the table (eg. goto or something else)

**Comment by usarid** [comment]
Go for it, @sichvoge ;-)

**Comment by sichvoge** [comment]
I think thats a duplicate for https://github.com/raml-org/raml-spec/issues/323. Closing this as `duplicate`.
