### ISSUE TITLE
Support "uses" in Typed Fragments

### ISSUE THREAD

**Issue by shlomiassaf** [raml-org/raml-spec#195]
Typed fragments should boost __Modularization__ significantly, yet their still not powerful enough.

For example, an API with a lot of __Types__ should be able to create a __DataType__ fragment file per type, this is a major improvement in terms of project maintainability & scalability, especially in teams where developers do the docs.
RAML 1.0 allows that but each file is isolated from the world, it has no reference to anything.

If one would like to use Typed fragments, it will have to make every type as a fragment, even custom types... using libraries is not an option.

The __DataType__ typed fragment should support "uses" so the fragment could get some context.

It should also be considered to allow a fragment to call "uses" to library that is the "parent" of that fragment, a recursion detector should be implemented. This is not crucial as "family members" of the same library can reference each other directly, if needed.

**Comment by usarid** [comment]
Every data type that you want to get some context could be defined within a Library, no?

**Comment by shlomiassaf** [comment]
Yes it can.

But the purpose of __DataType__ fragment is to allow even more modularity.
Lets say I have 100 types in my API, I can put all of them in a library but then I have a big 1 file hard to maintain.
I can categorize them into multiple libraries, but this isnt the ideal solution.

If we already have the DataType fragment, it should be powerful enough.
In my repo each type has its own file, I would like to match that to my API so a developer can easily access and edit that file, it makes the API project structure similar to the code structure.

**Comment by sichvoge** [comment]
I agree - inside a DataType you could even reference to another DataType that is defined inside a library.

**Comment by sichvoge** [comment]
Also -w/o `uses` in `DataType` I can't introduce potential annotations for example.

**Comment by shlomiassaf** [comment]
:+1:

**Comment by sichvoge** [comment]
fix will be introduced with #226

**Comment by usarid** [comment]
@shlomiassaf I'm hoping that this part of #226 addresses your concerns:
> This proposal also expands the use of uses to allow its use in a root ("master") RAML file as well as in all RAML fragment files.
Let us know if you agree and we'll look to close this issue.

**Comment by sichvoge** [comment]
Closing that as it has been addressed by #226 and put into RC2.
