### ISSUE TITLE
Example expanded equivalent in "Shortcuts and Syntactic Sugar" is wrong

### ISSUE THREAD

**Issue by mtritschler** [raml-org/raml-spec#197]
The expanded version of
```yaml
    Email:
```
is mistakenly given as 
```yaml
    Age:
      type: number
```
http://docs.raml.org/specs/1.0/#raml-10-spec-shortcuts-and-syntactic-sugar

**Comment by sichvoge** [comment]
Thanks for reporting it. Will be fixed ASAP.

**Comment by sichvoge** [comment]
Also `Email: string` in the same section can be removed as it is already defined in the beginning of the table. (the 3rd row)
