### ISSUE TITLE
It looks like Overloading section is missing

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-spec#199]
We had a draft of language clarifying how overloading should work, but we do not have an overloading section here: http://docs.raml.org/specs/1.0/

**Comment by sichvoge** [comment]
According to PR #336; that section is actually not necessary as an additional section anymore. Due to YAML restrictions multiple keys with the same name should not be allowed anyways, and ambiguity around resources could be mentioned in the resource section.
