### ISSUE TITLE
Missing XMLInfo

### ISSUE THREAD

**Issue by gardea** [raml-org/raml-spec#205]
There's an optional *xml* property that a type declaration object may have. Its value type is **XMLInfo** and it doesn't seem to be described anywhere else in the document. What is it?

**Comment by sichvoge** [comment]
That came from the idea to have some help to serialise XML data. As we did some testing on our new type system and how we are serialising them into different formats, we realised that this definitely needs more discussion and should not be part of the spec for now. We need to make things definitely very clear before bringing it in. I might create a separated channel and we could share some ideas around that if you like. 

For now, we will remove that facet from the spec until we all discussed that and are on the same page. Thanks for raising it. :)

**Comment by sichvoge** [comment]
Its described here now https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#xml-serialization-of-type-instances
