### ISSUE TITLE
Possible typo in describing uriParameters

### ISSUE THREAD

**Issue by gardea** [raml-org/raml-spec#206]
> If a URI parameter declaration specifies an array or object type for the value of the header, ...

What is **the value of the header** doing here?

Similarly:

> If a URI parameter declaration specifies a non-string scalar type for the value of the header

Please clarify.

**Comment by sichvoge** [comment]
Probably a typo - i think we can remove `for the value of the header` as it should be clear that what that implies to is the URI parameter. What do you think?

`for the value of the header` -> I think what is meant here is basically the URI parameter type.

**Comment by gardea** [comment]
> If a URI parameter declaration specifies an array or object type for the value of the header, or if it specifies a union type of non-scalar types, then processors...

could become:

> If a URI parameter declaration specifies an array, object, or union of non-scalar types, then processors... 

I would then add a wire example to further the meaning.

**Comment by sichvoge** [comment]
We can change that easily, but can you provide that example pls? That would help to make that happen much quicker.

**Comment by gardea** [comment]
I am not so sure about the intent myself; I would assume that for this fragment:

    queryParameters:
      labels:
        description: List of Label names.
        type: array
        items:
          type: string
          minLength: 1
          uniqueItems: true

this would be the "default [...]  format of the URI parameter value as JSON" 

    ["blue","green"]

which then, on the **wire** may look as:

    ?labels=%5B%22blue%22,%22green%22%5D

If the above would be a correct interpretation of the intent, then object would spell itself.

However, I am reluctant to do it more as I believe examples for a spec should come from one or two example RAMLs written specifically to cover *all* features and scenarios. In my experience the added benefit is in that there would be a consistent story throughout, and such adding to the cohesiveness of the story behind.

**Comment by petrochenko-pavel-a** [comment]
@gardea serialisation of the types is still something that should be improved. Original intent was to provide some consistent way of serialisation which works somehow in all possible positions where data types may occur and allow customisation of it using the annotations, but unfortunately it is something that still need to be refined

Regards,
Pavel

**Comment by gardea** [comment]
I agree with the intent; this is one feature we really like in 1.0 - a long time ago we've built extensions to support it for RAML 0.8, specifically for query parameters **only**.

In our specs we've described the string as returned by a JSON.stringify() call, and for which we've appropriately linked the corresponding JSON Schema.
