### ISSUE TITLE
Missing code block end ticks in "Resource Types and Trait Parameters"

### ISSUE THREAD

**Issue by matto1990** [raml-org/raml-spec#209]
In the [Resource Types and Traits Parameters](http://docs.raml.org/specs/1.0/#raml-10-spec-resource-type-and-trait-parameters) section of the 1.0 spec, the first code block is missing the closing markdown back-ticks. This makes the following paragraphs hard to read.

**Comment by sichvoge** [comment]
Very good catch. We will publish a new version on Friday where that is definitely part of it ;)

http://blog.raml.org/update-on-raml-1-0-and-tooling/
