### ISSUE TITLE
The in page link to Types->Introduction goes to the overall introduction

### ISSUE THREAD

**Issue by Relequestual** [raml-org/raml-spec#216]
The hash link for the 1.0 RC specification document introduction is repeated in the Types Introduction section table of contents on the left.

I'm happy to submit a pull reuqest for this if someone can direct me to where I can find the file.

**Comment by sichvoge** [comment]
Oops :) Good catch, we will publish a new version soon and put that in. thanks for raising.

**Comment by sichvoge** [comment]
This one is actually not relevant anymore - it was a problem of the previous content that was not MD.

**Comment by Relequestual** [comment]
Is the 1.0 RC2 spec in markdown now?

**Comment by sichvoge** [comment]
@Relequestual - we will switch off that page and redirect to https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md. Its a bit legacy. It is part of https://github.com/raml-org/raml-spec/wiki/RAML-1.0-RC2---Plan. That's why I closed that issue.

**Comment by Relequestual** [comment]
Sure. Sounds good!

I have to say though, I personally like it being featured on the site in that way.
Github markdown doesn't provide a table of content (which is one of my pet gripes with swagger spec documentation...).

**Comment by sichvoge** [comment]
I agree - we plan to add back a generated page after we GA, but we need to work a bit on the design and make the overall experience better.
