### ISSUE TITLE
Suggestion for restrictions on multiple inheritance

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [raml-org/raml-spec#218]
If look on the following sample
```raml
#%RAML 1.0 
title: My API With Types
types:
  Person:
    type: object
    properties:
      age:
        type: string
        required: true
        description: the age bucket they belong to
        repeat: false
        maxLength: 1
  Animal:
    type: object
    properties:
      age:
        type: integer
        repeat: true
        required: false
        
  User:
    type: [Person, Animal]
```
It becomes clearly visible that it is possible to inherit property with a different types/facets multiple times.
suggestion is to clarify directly in inheritance restriction that it should not be allowed.

**Comment by sichvoge** [comment]
http://stackoverflow.com/questions/995255/why-is-multiple-inheritance-not-allowed-in-java-or-c

**Comment by sichvoge** [comment]
That is basically invalid with the introduction of more simplistic inheritance rules #319
