### ISSUE TITLE
YAML 1.2 support

### ISSUE THREAD

**Issue by fededonna** [raml-org/raml-spec#221]
Spec says that RAML 1.0 support YAML 1.2. Yaml 1.2 says that every valid json is a valid yaml so this:

```json
{
  "/{personId}": {
    "get": null
  },
  "/people": {
    "get": {
      "body": {
        "application/json": {
          "type": "Animal",
          "example": {
            "age": -5
          }
        }
      },
      "responses": {
        "200": {
          "body": {
            "application/json": {
              "type": "Person"
            }
          }
        }
      }
    }
  },
  "types": {
    "Person": {
      "type": "object",
      "properties": {
        "age": {
          "required": true,
          "type": "string",
          "description": "the age bucket they belong to",
          "repeat": false,
          "maxLength": 1
        }
      }
    },
    "User": {
      "type": [
        "Person",
        "Animal"
      ]
    },
    "Animal": {
      "type": "object",
      "properties": {
        "age": {
          "minimum": 0,
          "type": "integer",
          "repeat": true,
          "required": false
        }
      }
    }
  },
  "title": "My API With Types"
}
```

Should be a valid API Definition.

IMHO we should go for YAML 1.1 and avoid this ambiguity.

**Comment by sichvoge** [comment]
@fededonna can you quickly describe again the problem. I am trying to understand what your main purpose is.

**Comment by fededonna** [comment]
I've never noticed that from RAML 0.8
The main problem is that they can use json instead of yaml and that is a valid yaml too. As the example shows above.

**Comment by sichvoge** [comment]
The question is what else would change when we switch back to 1.1?! I'd prefer to really think about that before making decisions.

**Comment by petrochenko-pavel-a** [comment]
only issue which I see with this definition after adding `"#%RAML 1.0"` and pasting it into API workbench t is `get: null` which looks pretty logical to me. May you please describe the problem in a little bit more details.

Thanks in advance,
Pavel

**Comment by sichvoge** [comment]
Are we going somewhere with this?

**Comment by fededonna** [comment]
Since raml 0.8 supports YAML 1.2 this discussion is going nowhere. So I'm closing it. Thanks.

**Comment by fededonna** [comment]
@usarid as @sichvoge pointed out to me before it does.
https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#overview

So that shouldn't be a big deal or it's a use case that no-one is using right now. So that's why I've closed this issue.
