### ISSUE TITLE
Change `uses` to act like "requires" in other languages

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#226]
The proposal is to change the semantics of `uses` to indicate that the remote library to be used is _available_ as a local asset, using a local namespace. 

Using `uses` does NOT automatically import the remote library's assets into the local file, but it allows the local file to import those assets by referring to them in its contents: e.g., a RAML type fragment file that `uses` a library of remote types can then import one of those types by referring to it, and that remote type will be included as if it were defined locally within the RAML type fragment file.

The namespaces defined in a `uses` statement in a file are only consumable within that file, i.e. they are only used to disambiguate the included libraries from each other within that file.

This proposal also expands the use of `uses` to allow its use in a root ("master") RAML file as well as in all RAML fragment files.

The `uses` keyword may ONLY be used at the root of a RAML file (either a root ["master"] RAML file or a RAML fragment file), and its value MUST be the location of a RAML library file.

This proposal is aimed to simplify the conceptual model of consuming libraries, and better support modularity of API definitions, e.g. by eliminating artificial dependency cycles (https://github.com/mulesoft/api-workbench/issues/29).

**Comment by petrochenko-pavel-a** [comment]
This is fine for me, but I remember a suggestion. In the current proposal the differences in behaviour of !include in uses and every where else will not be clear for anybody so  I suggest to use `masterRef` style of pointing to files in the `uses` to avoid confusion.

**Comment by sichvoge** [comment]
What do you mean @petrochenko-pavel-a?

**Comment by usarid** [comment]
You mean just omit the !include and have the value of each key in uses be a URL?






On Tue, Jan 19, 2016 at 4:28 AM -0800, "Christian Vogel" <notifications@github.com> wrote:












What do you mean @petrochenko-pavel-a?

**Comment by petrochenko-pavel-a** [comment]
>just omit the !include and have the value of each key in uses be a URL?
yep

**Comment by sichvoge** [comment]
Are we not coherent on our approach when we reference an external file? Isn't `masterRef` the only place right now where we omit `!include`? Are there any other places?

**Comment by petrochenko-pavel-a** [comment]
yes it is only place.

**Comment by sichvoge** [comment]
So shouldn't we more coherent on our approach and use the same approach everywhere else? Therefore, I would probably not omit `!include`

**Comment by usarid** [comment]
The `!include` behavior is different than the behavior here and in
overlays/extensions: in the former, you are pulling the external document
into the local file, while here and in overlays/extensions, you're
referring to the external document (albeit for different purposes).

**Comment by usarid** [comment]
I changed the proposal writeup to omit the `!include` tag and keep just the location of the library document as the value of `uses`.

**Comment by sichvoge** [comment]
@usarid are there any syntactical changes? if so, can you please give me an example.

**Comment by usarid** [comment]
It simply means that you don't use an `!include` to reference the libraries you'll potentially be using, any more than you need an `!include` to reference the master RAML document within an overlay or extension -- you just reference their location directly, without the `!include`. The rules for resolving the location of the document are the same whether the location is the value of an `!include` or the value of `uses` or the value of `masterRef`.

```raml
#%RAML 1.0
title: Users API
uses:
  common: //patterns.example.com/common.raml
  corp: //patterns.example.com/corp.raml
/users:
  type: common.Collection
  get:
    is:
      - corp.tracked
      - common.searchable
```
