### ISSUE TITLE
Change `masterRef` to `extends` in RAML overlays and extensions

### ISSUE THREAD

**Issue by usarid** [raml-org/raml-spec#228]
RAML overlay and extension fragments must reference the RAML file they build upon. They currently do so through the property named `masterRef`. This name is inconsistent with most RAML property names, which strive to be either common English words such as `title` or `trait` or common technical terms such as `baseUri` or `mediaType`. 

Instead of `masterRef`, I propose `extends`, as both overlays and extensions extend the original specification: overlays do so without changing the functional specification while extensions may change the functional specification.

**Comment by usarid** [comment]
Thanks @ProLoser for the prompting (https://github.com/raml-org/raml-spec/issues/227)

**Comment by ProLoser** [comment]
:+1:
