### ISSUE TITLE
Unclear how parsers should interpret nested vs non-nested resources

### ISSUE THREAD

**Issue by joshrosso** [raml-org/raml-spec#232]
The RAML spec should define how parsers interpret nested vs non-nested resources. Consider the following.

**[1]**

``` raml
/principals/{someUser}:
  get:
```

**[2]**

``` raml
/principals:
  {someUser}:
    get:
```

It's unclear as to how a parser should treat these relative to one another. In MuleSoft's own RAML parser, based on behaviors I've seen in APIKit, these are not functionally equivalent. Consider the following request.

``` bash
curl -X GET http://{host}:{port}/principals
```

**[1]** produces a `404` and **[2]** produces a `405`. At a minimum, RAML should provide direction on whether these MUST be considered equal. Possibly RECOMMEND they are interpreted as `405` since the resource does exist, but has 0 available methods.

/cc @FedeAmdan

**Comment by sichvoge** [comment]
I think that this could be related to #229

**Comment by sichvoge** [comment]
@joshrosso I'd like to keep track of that inside the previous issue #229. Closing it as `duplicate`
