### ISSUE TITLE
Allow defining multiple default media types

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#234]
Defining a default media type has been described in RAML 0.8 as a mechanism to define the default media type returned by API responses, and expected from API requests that accept a body. 

The proposal is to extend that to be able to define a list of default media types with the premise that all of them are described by exactly the same types and /or examples.

```yaml
#%RAML 1.0
title: New API
mediaType: [ application/json, application/xml]
types:
  Person:
/list:
  get:
    responses:
      200:
        body: Person[]
/send:
  post:
    body: Person
```

The equivalent RAML to the example above is:

```yaml
#%RAML 1.0
title: New API
types:
  Person:
/list:
  get:
    responses:
      200:
        body:
          application/json: Person[]
          application/xml: Person[]
/send:
  post:
    body:
      application/json: Person
      application/xml: Person
```

If you have cases where you need to override the default behaviour, you MAY define media types explicitly when describing your API response or request. The following example illustrates that:

```yaml
#%RAML 1.0
title: New API
mediaType: [ application/json, application/xml]
types:
  Person:
  Another:
/list:
  get:
    responses:
      200:
        body: Person[]
/send:
  post:
    body:
      application/json:
        type: Another
```

**Comment by usarid** [comment]
To further clarify: when you define a root-level `mediaType` and then override that in a `body` by defining explicitly a media type node, **none** of the root level media types apply to that node, other than the media types explicitly defined within that node -- that is, when you override, you're overriding everything, and need to explicitly define each and every media type within that node.

**Comment by fededonna** [comment]
Hi, what about this example?

`
#%RAML 1.0
title: New API
mediaType: [ application/json, image/png]
types:
  Person:
/list:
  get:
    responses:
      200:
        body: Person[]
/send:
  post:
    body: Person
`

The mediaType of the "send" and "list" resources are both listed in the default. How do I validate if they send an image? shouldn't we restrict the default only to a type that can be converted to the type-system?

**Comment by usarid** [comment]
No, in fact one may use any schemas in RAML 0.8 and 1.0, not just XML Schema and JSON Schema and RAML data types; it's just that parsers are only required to support XML Schema and JSON Schema and RAML data types. And similarly one can use any media type for the defaults or for the bodies, and parsers are only required to validate the relevant combinations of XML, JSON, and XML Schema and JSON Schema and RAML data types. In your example, you probably won't validate an image if one is sent; it's also probably not a very meaningful API design :-)

**Comment by fededonna** [comment]
Great, thanks. We should clarify what is a RAML data type. Is it a json/xml representation of the object or does RAML (parser more specifically) also validates binary object representations like serialized objects?

**Comment by sichvoge** [comment]
As by some discussions on PR #282; we decided to keep the name `mediaType` instead of using `mediaTypes` and also give end users possibility to either define a single media type represented as a single string (like in 0.8) or multiple represented as a sequence (`[]`).
