### ISSUE TITLE
Clarification question on typed fragments

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#240]
Looking at section http://docs.raml.org/specs/1.0/#using-applying-annotations and the available Typed Fragments I am wondering why `Api` is a type fragment when it relates to a root RAML. Currently these two are the same:

```yaml
#%RAML 1.0 API
title: API Fragment
```

```yaml
#%RAML 1.0
title: API
```

Shouldn't we prevent the `API` fragment?

**Comment by usarid** [comment]
`API` is a possible target location but it is not a [fragment identifier](http://docs.raml.org/specs/1.0/#typed-fragments) so `#%RAML 1.0 API` is never a valid construct in RAML.

**Comment by sichvoge** [comment]
OK. It's clear inside the specification and more a parser problem. Closing it.
