### ISSUE TITLE
Support for Type Composition

### ISSUE THREAD

**Issue by mavam** [raml-org/raml-spec#243]
It appears that composition of types currently does not work. Apologies for re-iterating on a topic [from the forums](http://forums.raml.org/t/recursive-data-types/1122), but I could not find a viable discussion base. Let me illustrate my point:

```raml
#%RAML 1.0
types:
  T: boolean | integer
  U: T | string
```

The apiworkbench compiler complains with:

```
Extending from types extending union types is not allowed
```

I trace this back to the section *Inheritance Restrictions*, where the spec says: *You cannot inherit from types extending union types ( ex: you cannot extend from `Pet` if `Pet = Dog | Cat` )*. 

Am I missing something here or is composition really forbidden? If so, why? Composition is vital to a modular spec. Without composition, data types will remain of limited use with a few basic types. It's great to see strong typing move forward with 1.0. It gives rise to new forms of type safety, which lead to more robust APIs.

**Comment by sichvoge** [comment]
Its not really forbidden anymore. We have loosen the restrictions on inheritance in the GA version already and your example is valid.

**Comment by mavam** [comment]
Great to hear!
