### ISSUE TITLE
Add displayName to a specific declaration of `securitySchemes`; and remove `description` and `displayName` in `describedBy`

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#244]
In RAML 1.0 RC, the `describedBy` property of a security scheme has two additional properties `description` and `displayName`. My question is if we really need them to be there? A specific security scheme already has a `description` property and, IMHO, that makes the one in `describedBy` redundant. I also would understand if we move `displayName` up to the security scheme property as well, but it should not be in `describedBy`.

Happy to hear other opinions.

**Comment by usarid** [comment]
It should have neither a description nor a displayName

**Comment by sichvoge** [comment]
You mean in `describedBy`, right? What about a security scheme? 

Example:

```yaml
securitySchemes:
  - oauth_2_0:
      displayName: OAuth 2.0 Authentication
      description: |
          Dropbox supports OAuth 2.0 for authenticating all API requests.
      type: OAuth 2.0
      describedBy:
          headers:
              Authorization:
                  description: |
                     Used to send a valid OAuth 2 access token. Do not use
                     with the "access_token" query string parameter.
                  type: string
          queryParameters:
              access_token:
                  description: |
                     Used to send a valid OAuth 2 access token. Do not use together with
                     the "Authorization" header
                  type: string
          responses:
              401:
                  description: |
                      Bad or expired token. This can happen if the user or Dropbox
                      revoked or expired an access token. To fix, you should re-
                      authenticate the user.
              403:
                  description: |
                      Bad OAuth request (wrong consumer key, bad nonce, expired
                      timestamp...). Unfortunately, re-authenticating the user won't help here.
      settings:
        authorizationUri: https://www.dropbox.com/1/oauth2/authorize
        accessTokenUri: https://api.dropbox.com/1/oauth2/token
        authorizationGrants: [ authorization_code, refresh_token ]
```

**Comment by usarid** [comment]
The security scheme has them, the describedBy does not 






On Fri, Feb 12, 2016 at 8:15 AM -0800, "Christian Vogel" <notifications@github.com> wrote:












You mean in describedBy, right? What about a security scheme? 



Example:

securitySchemes:
  - oauth_2_0:
      displayName: OAuth 2.0 Authentication
      description: |
          Dropbox supports OAuth 2.0 for authenticating all API requests.
      type: OAuth 2.0
      describedBy:
          headers:
              Authorization:
                  description: |
                     Used to send a valid OAuth 2 access token. Do not use
                     with the "access_token" query string parameter.
                  type: string
          queryParameters:
              access_token:
                  description: |
                     Used to send a valid OAuth 2 access token. Do not use together with
                     the "Authorization" header
                  type: string
          responses:
              401:
                  description: |
                      Bad or expired token. This can happen if the user or Dropbox
                      revoked or expired an access token. To fix, you should re-
                      authenticate the user.
              403:
                  description: |
                      Bad OAuth request (wrong consumer key, bad nonce, expired
                      timestamp...). Unfortunately, re-authenticating the user won't help here.
      settings:
        authorizationUri: https://www.dropbox.com/1/oauth2/authorize
        accessTokenUri: https://api.dropbox.com/1/oauth2/token
        authorizationGrants: [ authorization_code, refresh_token ]

**Comment by sichvoge** [comment]
OK - just to mention; the property `displayName` would be new to the security scheme property. That wasn't there before.

**Comment by usarid** [comment]
Ah, I see. I don't feel strongly but it seems consistent and useful to give
it a displayName for tooling purposes.

**Comment by sichvoge** [comment]
LGFM :+1:
