### ISSUE TITLE
RAML allows to include libraries in traits and resourceTypes, but ...

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#249]
The current RC1 version declares that a trait and resourceType node has also the `uses` key that can be used to include libraries. That makes a lot sense if you are using a typed fragment, but not if you define those as root-level nodes inside an API. Is it not possible to say that there is a type fragment node that always contains the usual suspects such as `uses` and then there are different forms that extend from that like a typed fragment for traits and so on?

**Comment by petrochenko-pavel-a** [comment]
according to #226 `uses` will be removed from concrete nodes definition and will be replaced by generic `require` like mechanism. so I guess issue is solved by #226

**Comment by sichvoge** [comment]
Where will that generic `require` be placed?

**Comment by sichvoge** [comment]
OK, get it. After reading #226 its clear that `uses` will be only available at the root-level in the future. 

> The uses keyword may ONLY be used at the root of a RAML file (either a root ["master"] RAML file or a RAML fragment file), and its value MUST be the location of a RAML library file.

Closing that issue.
