### ISSUE TITLE
Remove either usage or description in several RAML nodes

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#250]
In some places in the current version of the RAML specification (1.0 RC1) there are `usage` and `description` both available. As far as I understand, both have the same meaning and therefore we should think about removing one in favour for the other. 

Based on [this comment](https://github.com/raml-org/raml-spec/issues/227#issuecomment-176923611) and the question [here](https://github.com/raml-org/raml-spec/issues/223), we should remove `usage` and consistently use `description`.

**Comment by sichvoge** [comment]
Examples are `traits` and `resourceTypes` btw.

**Comment by svacas** [comment]
`usage` and `description` behave different in resource types and traits, as `usage` is not merged in the target resource/method but `description` it is merged. I find this a bit puzzling as one may think that the `description` is for the resource type or trait itself and not something to be merged in the target element.
IMHO to avoid ambiguities `description` should be forbidden at the top level of a resource type/trait, and only `usage` be allowed.

**Comment by usarid** [comment]
Indeed `usage` is used in resource types and traits as a description of when and where the resource type or trait should be used, while `description` must NOT be allowed to be used in resource types and traits so it does not override the `description` field in the resources and methods to which these resource types and traits are applied.

**Comment by sichvoge** [comment]
Why should `description` be not allowed in resource types? This was always a huge advantage as you could easily create a simple description using parameters such as `<<resourcePathName>>``. That made a lot of things really simple. So I would vote against removing it from a resource type node.

**Comment by usarid** [comment]
Fair point, though you might make the same case about `displayName`, and add it in here, no?

**Comment by sichvoge** [comment]
No not really as it defaults to the resource path name anyways ;) IMHO, `description` has it's reason to be there.

**Comment by sichvoge** [comment]
So, actually nothing has to be changed here right? @usarid 

My mistake was that I compared `usage` and `description` as similar nodes, but they aren't since `description` is a node that applies to resources or methods whereas `usage` is the description for the resource type or trait. So I would say, let's close this issue as invalid.

**Comment by usarid** [comment]
Just to be clear, we'll allow `displayName` and `description` on resource types and traits, which means they will dictate `displayName` and `description` values to any resources and methods that use them -- those resources and methods can then override those values if needed.

**Comment by sichvoge** [comment]
Thanks for clarification Uri. Closing this as nothing changes.
