### ISSUE TITLE
Spec is not really clear about behaviour of securedBy on resources

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#251]
Are security schemes applied to a resource also automatically applied to all nested resources?

**Comment by usarid** [comment]
No, they don't - nor do nested resources inherit anything else from platen resources, except things they manifestly share like the common parts if their paths, base URIs, and globals.






On Fri, Feb 19, 2016 at 4:22 AM -0800, "Christian Vogel" <notifications@github.com> wrote:












Are security schemes applied to a resource also automatically applied to all nested resources?

**Comment by sichvoge** [comment]
Thanks for clarification @usarid. We should make that behaviour clearer in RC2.

**Comment by usarid** [comment]
There is no reason security schemes should be treated any differently than traits or resource types, and those too don't apply to nested resources. Nevertheless, sure, let's be more explicit. We already have the following language:
Resource type definitions MUST NOT incorporate nested resources; they cannot be used to generate nested resources when they are applied to a resource, and they do not apply to its existing nested resources.
Let's take the last phrase and explicitly use it also for traits and security schemes, and anything else you think might not be clear enough.






On Fri, Feb 19, 2016 at 5:58 AM -0800, "Christian Vogel" <notifications@github.com> wrote:












Thanks for clarification @usarid. We should make that behaviour clearer in RC2.
