### ISSUE TITLE
raml integration from jooby

### ISSUE THREAD

**Issue by jknack** [raml-org/raml-spec#254]
Tool is available at http://jooby.org/doc/raml with a live demo at https://jooby-spec.herokuapp.com/raml

I would love to see my tool listed at http://raml.org/projects/projects but I couldn't find where to post this (or where to send a pull request)

**Comment by sichvoge** [comment]
Hi @jknack, there is a handy little button on the projects page to submit your own. ;)

![image](https://cloud.githubusercontent.com/assets/498114/13249184/bd848d18-da1a-11e5-9577-b263f4456d0c.png)

**Comment by jknack** [comment]
How could I miss it!!!!

Thanks!!!
