### ISSUE TITLE
Repeatable headers

### ISSUE THREAD

**Issue by Biribu** [raml-org/raml-spec#255]
0
down vote
favorite
I want to include a repeteable header in my resource.

Now I am working over an example I created:

This is the result and the red lines mean what I want to achieve if possible:
![repeatable](https://cloud.githubusercontent.com/assets/1679476/13348937/d81ea3d0-dc76-11e5-9666-4767f5fbe097.PNG)

I want the user could create multiple "bla" fields with a "+" button and remove them with a "X" button. Is it possible?

This is my raml code for this example:

#%RAML 0.8
title: bla
baseUri: http://localhost/
version: v1
mediaType:  application/json

/foo:
  get:
    headers:
      bla:
         type: string
         required: false
         repeat: true
         description: description

**Comment by sichvoge** [comment]
You might want to ask the question in mulesoft/api-console if that is directly related to that.

**Comment by Biribu** [comment]
Thank you, I will ask there

**Comment by sichvoge** [comment]
Thanks! Hope it gets resolved.
