### ISSUE TITLE
Adding resourceTypes functions table and more details to all.

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#268]
The current RC1 version does not describe all functions that can be applied to resource type parameter in much details. Only the first two. Let's add a bit more descriptive text to the others as well.

![image](https://cloud.githubusercontent.com/assets/498114/12970643/5667191a-d089-11e5-9bd0-b77f997d1738.png)

**Comment by blakeembrey** [comment]
Seems like a good idea. Honestly, this should be specced entirely to get consistent implementations. For example, do these methods consider all languages and letter characters in those languages? What characters does one break on to make it camel case?

**Comment by sichvoge** [comment]
@blakeembrey @usarid should we restrict "United States English" as in the first two functions? I can change that in my current PR
