### ISSUE TITLE
Do we restrict resource type parameter functions to a specific language?

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#278]
As per @blakeembrey 's comment in https://github.com/raml-org/raml-spec/issues/268#issuecomment-191338807. Are we focusing on a specific language? These are implementation details that we should clarify.

**Comment by usarid** [comment]
United States English.

**Comment by sichvoge** [comment]
@blakeembrey do we need to take care of anything else since you mentioned UTF8?

**Comment by blakeembrey** [comment]
Not if it's only US English since that's only a ASCII subset. If we were to support other characters in the camel casing it would be relevant to link to the specifications for character subset support. For example, http://www.fileformat.info/info/unicode/category/Ll/list.htm.

**Comment by sichvoge** [comment]
Cool thanks Blake.
