### ISSUE TITLE
Improve annotation target table

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#283]
Currently, names and description inside the annotation table are not very clear. Let's improve them.

**Comment by sichvoge** [comment]
How about:

```
Api
DocumentationEntry
Resource
Method
RequestBody
ResponseBody
TypeDeclaration
Scalar
Example
ResourceType
Trait
SecurityScheme
SecuritySchemeSettings
AnnotationType
Library
Overlay
Extension
```

**Comment by usarid** [comment]
Let's keep using `API` (not `Api`) and `DocumentationItem` (not `DocumentationEntry`). But before we finalize, as this is somewhat different list than what's in the RC1 spec, could you put here the entire table including their descriptions, and we can make sure we're talking about the same things? For example let's recall here why we're choosing `Scalar` and not `TypeDeclaration`.

**Comment by sichvoge** [comment]
This is the complete table we have right now.

|Target | Description |
|:--------|:------------|
| API | The root of a RAML document
| DocumentationItem | An item in the collection of items that is the value of the root-level documentation property.
| Resource | A resource (relative URI) property, root-level or nested
| Method | A method property
| Response | A property of the responses property, whose key is an HTTP status code
| RequestBody | The body property of a method
| ResponseBody | The body property of a response
| TypeDeclaration | A data type declaration (inline or in a global types collection), header declaration, query parameter declaration, or URI parameter declaration, or property within any of these declarations, where the type property may be used.
| Scalar | A scalar-valued node listed in [Annotating Scalar-valued Nodes](#scalar-valued-nodes).
| NamedExample | A property of the examples property, whose key is a name of an example and whose value describes the example.
| ResourceType | A resource type property
| Trait | A trait property
| SecurityScheme | A security scheme declaration
| SecuritySchemeSettings | The settings property of a security scheme declaration
| AnnotationTypeDeclaration | A property of the annotationTypes property, whose key is a name of an annotation type and whose value describes the annotation.
| Library | The root of a library declaration.
| Overlay | The root of an overlay declaration.
| Extension | The root of an extension declaration.

`Scalar` had been introduced with #225.

**Comment by usarid** [comment]
OK, I see, I don't believe we need `scalar` at all, I see no value in giving a special category to all scalar-valued nodes to allow annotations to target them specifically, since they don't as a class serve some particular functional purpose. Otherwise the table looks good as is.
