### ISSUE TITLE
Merging process of optional query parameter in traits is counter-intuitive

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-spec#292]
Due to the following wordings in the spec, located in Optional Properties subsection of Resource Types and Traits section:
>To accommodate this need, a resource type or trait definition MAY append a question mark ("?") suffix to the name of any object-valued property that should not be applied if it doesn't already exist in the resource or method at the corresponding level. A property is considered object-valued if its value is of type object or of a type that has object at the base of its inheritance hierarchy. The question mark suffix indicates that the value of the property in the resource type or trait should be applied if the property name itself (without the question mark) is already defined (whether explicitly or implicitly) at the corresponding level in that resource or method.

optional query parameter defined in a trait is not merged into a method unless such parameter is already defined in the method itself.

This is not something users expect.

**Comment by ddenisenko** [comment]
Here's the initial input from Uri:

we should clarify: optional properties are supposed to be for methods, and then at some point we thought: hey, why not say it's for everything? But that's before we have ? for anything else and before we had data types. So maybe we should restrict it back down to methods again.

**Comment by ddenisenko** [comment]
Well, the current version contains exactly the quoted wordings. So if we agree that optional query parameters should be merged, that wordings should be restricted (either to methods only, or may be someone can come up with a broader restriction still covering query parameters).

**Comment by sichvoge** [comment]
If we restrict it to methods, optional properties will only be available for resource types. Do we have any use cases where we would need these mechanism in traits. I haven't seen any so far, but maybe someone else knows.

**Comment by usarid** [comment]
You could probably make a case for the items under `responses` (i.e. *if* a method defines a `201` *then* it should behave as follows) and for the items under `securedBy` (i.e. *if* you're secured by OAuth *then* use the following), but for simplicity I would restrict it to just methods, which means as you say that it only applies to resource types.

**Comment by sichvoge** [comment]
OK - will apply that for RC2. Thanks all!
