### ISSUE TITLE
Clarify that `schema` and `type` are mutually exclusive

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#308]
RAML 1.0 RC2 should clearly state that `schema` and `type` are mutually exclusive. Therefore, the following should be invalid in any future version of RAML.

```yaml
/resource:
  get:
    responses: 
      200:
        body: 
          application/json:
            schema: 
            type:
```

You are still allowed to have global definitions for `schemas` or `types`, although it is recommended to use `types` only.

**Comment by svacas** [comment]
What's the suggested approach for users that already have their entities in XML schema and/or JSON schema?

**Comment by usarid** [comment]
They can keep using them and just refer to them with the keyword `type` or `types` (which are not deprecated, vs their synonyms `schema` and `schemas` which _are_ deprecated), or they can see if they can model their data in RAML data types now.
