### ISSUE TITLE
Resource definition ambiguity

### ISSUE THREAD

**Issue by apomelov** [raml-org/raml-spec#32]
Hello.
I'm trying to resolve ambiguity of resource definition.
Assume I have the resource /a/b. The Raml spec says that I _should_ use nested resource if /a is a resource itself. If not I can use /a/b. Both ways are correct. But the spec does not prohibit (or I missed it) api like this:

```
/a:
  /b: !include b1.raml
/a/b: !include b2.raml
```

IMHO spec should explicitly say "Any described resource MUST have an unique absolute URI". I've found out that api-disigner marks my sample as error. But java raml parser does not.

**Comment by sichvoge** [comment]
A duplicate for https://github.com/raml-org/raml-spec/issues/229. Lets keep only one!
