### ISSUE TITLE
Are you allowed to pull in libraries in global definitions such as traits and resource types?

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#341]
Currently, the RC1 spec allows to define `uses` and therefore bringing in libraries inline. Are we really gonna allow that? If yes, why do would we allow that?

![image](https://cloud.githubusercontent.com/assets/498114/14138655/639f51a8-f666-11e5-9da5-9a07ab4f1750.png)
 
IMHO, that should not be allowed since I don't really see any use cases to do that on any global declaration.

**Comment by usarid** [comment]
I thought we settled definitely that `uses` can only be applied at the root level of a document (RAML file or fragment), so it could not be used within the `traits` or `resourceTypes` declaration. Please clarify with @petrochenko-pavel-a

**Comment by petrochenko-pavel-a** [comment]
@usarid @sichvoge as well as I remember `uses` is a top level property defined for any fragment now.

**Comment by sichvoge** [comment]
Thanks for clarifying Pavel.
