### ISSUE TITLE
Reference to inner elements may produce invalid schemas

### ISSUE THREAD

**Issue by svacas** [raml-org/raml-spec#376]
Raml 1.0 allows includes with fragment identifiers, though it's not clear what's the final content that should be included. In order to have valid schemas the entire file needs to be included.

An alternative is to use a global type and specify the fragment when the type is used:

```raml
types: 
    item: !include schema.xsd
...
    type: item#item    
```

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="title" type="xs:string"/>
<xs:element name="quantity" type="xs:positiveInteger"/>
<xs:element name="price" type="xs:decimal"/>

<xs:element name="item">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="title"/>
      <xs:element ref="quantity"/>
      <xs:element ref="price"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema> 
```

**Comment by svacas** [comment]
duplicates #375

**Comment by petrochenko-pavel-a** [comment]
As for me correct solution is to auto transform XSD when needed. So in case of element, you should take original XSD and add global element with appropriate type to it.
