### ISSUE TITLE
Using ~ when libraries are required

### ISSUE THREAD

**Issue by thenanox** [raml-org/raml-spec#381]
Hello,

I've been following the issues and the RC2 branch. I know about issue #226 which permits to use libraries inside RAML fragments that fix some of my problems.

The thing is i don't  really know after all the reading if importing with ~ is valid so no namespace is required for the library. In #207 and #204 is mentioned too.

For example: 
```
uses:
  - !include lib1.raml#Person
  - !include lib3.raml#Annotation1

/resource:
  (Annotation1): something
  get:
    responses: 
      200:
        body: 
          application/json:
            type: Person
```

I'm trying to anticipate how this will be handled so when API-workbench applies the RC2, it will be working properly

**Comment by sichvoge** [comment]
No using `~`  to avoid not using namespaces is not permitted with RC2.

**Comment by thenanox** [comment]
ok. i was interested in an alternative like that because parsers includes this prefix in the object generated, so i would need to work on them previously to generate the html for my documentation. At least #226 fix the RAML fragment libraries problems that is so needed for data types! :)
