### ISSUE TITLE
RAML spec grammar?

### ISSUE THREAD

**Issue by gtrevg** [raml-org/raml-spec#39]
I wondering if a grammar could be defined for the RAML spec.  If one were defined, any language that supports parsing of that grammar would then be able to create an Abstract Syntax Tree, thus allowing for more parsers in more languages more quickly.  In particular, I was looking at using some of the Go tools ( `go tool yacc raml_grammar.txt` ) in order to do some Go code generation.

Thanks

**Comment by sichvoge** [comment]
Thats a duplicate for https://github.com/raml-org/raml-spec/issues/208. Lets keep only one alive.
