### ISSUE TITLE
`Applying Libraries` example does not validate

### ISSUE THREAD

**Issue by j-funk** [raml-org/raml-spec#429]
I was having considerable trouble getting `uses` with `!include` to pass validation using `raml-js-parser-2`. So I decided to try parsing the example from the [latest documentation](https://github.com/raml-org/raml-spec/blob/raml-10-rc2/versions/raml-10/raml-10.md#applying-libraries) and see if it passed validation. To my surprise the example throws errors when run through the parser.  

Any feedback is much appreciated, since I cannot proceed with RAML 1.0 on our API until this is resolved.

[Here's a Github repo with the example setup](https://github.com/j-funk/raml-1.0-parser-test) to make it quick to diagnose / reproduce (or fix).

Some other notes which will hopefully be of help since they may be mistakes in the documented example:
 - Tried adding `[ ]` to all contents of `is:` since parser requires contents of `is:` to be a list
 - Tried adding `!include` to the `uses:` imports, not sure if you can import without using `!include`
 - Tried removing `libraries` from the import in `files.raml` since it is in the same directory

The code, as it stands in the example, give the following 3 errors. With the notes above I was able to reduce it to a single error.  

```
{
  "code": 9,
  "message": "node files can not be a scalar",
  "path": "index.raml",
  "start": 45,
  "end": 49,
  "line": 3,
  "column": 2,
  "range": [
    {
      "line": 3,
      "column": 2,
      "position": 45
    },
    {
      "line": 3,
      "column": 6,
      "position": 49
    }
  ],
  "isWarning": false
}
{
  "code": 11,
  "message": "property 'is' must be an array",
  "path": "index.raml",
  "start": 45,
  "end": 49,
  "line": 3,
  "column": 2,
  "range": [
    {
      "line": 3,
      "column": 2,
      "position": 45
    },
    {
      "line": 3,
      "column": 6,
      "position": 49
    }
  ],
  "isWarning": false
}
{
  "code": 0,
  "message": "Unrecognized trait 'files.drm'.",
  "path": "index.raml",
  "start": 45,
  "end": 49,
  "line": 3,
  "column": 2,
  "range": [
    {
      "line": 3,
      "column": 2,
      "position": 45
    },
    {
      "line": 3,
      "column": 6,
      "position": 49
    }
  ],
  "isWarning": false
}
```

**Comment by petrochenko-pavel-a** [comment]
>Tried adding !include to the uses: imports, not sure if you can import without using !include

actually you can not use !include with uses any more.

>Tried removing libraries from the import in files.raml since it is in the same directory
yep. it is treated as relative path.

please note that you should use rc2 branch to test it.

Regards,
Pavel

**Comment by j-funk** [comment]
Thanks, will check it out.

**Comment by j-funk** [comment]
@petrochenko-pavel-a  when I install `rc2` using the following `package.json` and `npm install`:
```
{
  "dependencies": {
    "raml-1-parser": "git://github.com/raml-org/raml-js-parser-2.git#rc2"
  }
}
```

I get the following error when I try to run the tests (the same tests pass when I use master).  
```
node node_modules/raml-1-parser/test/test01.js
RAML 1.0 JS Parser Test
module.js:338
    throw err;
    ^

Error: Cannot find module '../dist/index'
```

**Comment by sichvoge** [comment]
@j-funk as @petrochenko-pavel-a said, your example is mixing RC1 with RC2 I am afraid. The branch that Pavel pointed to is the current development branch that should give you what you need. 

What the repo you are using is missing, is the `dist` repo. I would recommend to clone and checkout the rc2 branch, and run `npm install`, `typings install`, and `npm link`. After that go to your project and execute `npm link raml-1-parser`. Its working for me.

**Comment by petrochenko-pavel-a** [comment]
basically to run against `rc2` you also need `raml-definition-system` from `develop` branch linked to `raml-type-system` from `rc2` branch. Every repo is a type script repo so you also need to transplile everything by running `npm run build` on each repo.

We are planned to have an internal release today so it is planned that we will do a prebuild snaphot to the end of Friday.

Regards,
Pavel

**Comment by sichvoge** [comment]
As I think that this is a parser problem, lets continue there. Please find the link [here](https://github.com/raml-org/raml-js-parser-2/issues/118).
