### ISSUE TITLE
Spec should explicitly say that it is allowed to configure `displayName` for the types derived from XSD/JSON schemas

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [raml-org/raml-spec#477]
Current spec text says the following:

```A RAML processor MUST not allow types that define an XML or JSON schema to participate in type inheritance or specialization, or effectively in any type expression. Therefore, you cannot define sub-types of these types to declare new properties, add restrictions, set facets, or declare facets. You can, however, create simple type wrappers that add annotations, examples, or a description.```

So it looks like it is not allowed to configure `displayName` for external types(https://github.com/raml-org/raml-js-parser-2/issues/156) , however it is pretty clear that ability to configure `displayName` is similar to configuration of `description` so it seems that we should correct spec text a bit and explicitly say that you can configure `displayName` for this kind of types.

Regards,
Pavel

**Comment by usarid** [comment]
Yes, thanks, and in fact please take a moment to confirm there are no more such cases we'll need to make explicit before GA.

**Comment by sichvoge** [comment]
We did; there is nothing else!
