### ISSUE TITLE
Overlay fails to parse due to type override

### ISSUE THREAD

**Issue by nialdarbey** [raml-org/raml-spec#486]
When I extend my API with an Overlay, it fails with the errors that I have attached as screenshots.
[My_Álainn_Cosmetics_Mobile_API-v1.0 (8).zip](https://github.com/raml-org/raml-spec/files/263486/My_Alainn_Cosmetics_Mobile_API-v1.0.8.zip)
<img width="632" alt="screen shot 2016-05-13 at 7 32 37 am" src="https://cloud.githubusercontent.com/assets/402424/15251620/2cec6c90-18df-11e6-8253-5f6f29f70466.png">
<img width="607" alt="screen shot 2016-05-13 at 7 42 46 am" src="https://cloud.githubusercontent.com/assets/402424/15251621/2cfc1ea6-18df-11e6-86f0-5e101030c77b.png">

**Comment by sichvoge** [comment]
Closing it since its not spec related. Created a new issue on the parser. https://github.com/raml-org/raml-js-parser-2/issues/177
