### ISSUE TITLE
How to specify a media type without enforcing any type

### ISSUE THREAD

**Issue by svacas** [raml-org/raml-spec#500]
In RAML 0.8 you could define a media type without schema to allow everything.
RAML 1.0 defaults to `string` type when no explicit type is defined.
How can we achieve the same for RAML 1.0?
e.g:

``` raml
#%RAML 0.8
title: media type with no type that allows any payload
baseUri: http://localhost/
/user:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {"name":"jane"}
```

**Comment by petrochenko-pavel-a** [comment]
Looking in the spec:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#determine-default-types

>The default type any is applied to any body node that does not contain properties, type, or schema. For >example:

Regards,
Pavel

**Comment by machaval** [comment]
I don't see the type any described in any place. Neither in the chart nor in the list of types. Is it a type that the user can define by hand?

**Comment by sichvoge** [comment]
It's basically the base type of all built-in types. We should clarify that a bit more. Pavel, can you send a PR on that?

**Comment by sichvoge** [comment]
Should be clarified https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#the-any-type.

**Comment by sichvoge** [comment]
Its related to #506
