### ISSUE TITLE
!lowercamelcase example probably should not be userId --> userId

### ISSUE THREAD

**Issue by hillazz** [raml-org/raml-spec#513]
Hi!
Probably the example should be UserId --> userId but not userId --> userId. This can be found in "Resource Type and Trait Parameters" chapter.

Thanks!

**Comment by sichvoge** [comment]
Happy to accept any PR ;)

**Comment by hillazz** [comment]
Hi, here is the PR: https://github.com/raml-org/raml-spec/pull/519

**Comment by sichvoge** [comment]
Thanks!
