### ISSUE TITLE
[1.0] API definition in separate files

### ISSUE THREAD

**Issue by codercms** [raml-org/raml-spec#515]
Hello! Is it possible to define API in separate files?
For example i want to define "issues" in issues.raml file and "users" in users.raml.
Thanks.

**Comment by sichvoge** [comment]
It is possible using `!include` and purely what YAML provides you. For example,

```yaml
/users: !include users.raml
```

Please be aware that it is not an official mechanism and on the tooling side you will loose the validation support during design time.

**Comment by codercms** [comment]
@sichvoge hm, okay, i created users.raml and added to api.raml following entry - `/users: !include users.raml`
And now i've got errors - i cannot deifne users.raml without required property title. But when i declaring title property i've got error in api.raml - Unknown node: title in users.raml.

**Comment by sichvoge** [comment]
If you do the following:

api.raml

```yaml
#%RAML 1.0
title: Test

/users: !include users.raml
```

users.raml

```
get:
```

That should work fine. If you use the workbench you might get errors inside users.raml, please ignore them.

**Comment by codercms** [comment]
@sichvoge thanks, the problem is solved!
