### ISSUE TITLE
Make scopes optional

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-spec#557]
As per #536 `scopes` is an optional property in OAuth 2.0 spec and we should respect that. Currently its required in the RAML spec and we should change that.

**Comment by n2ygk** [comment]
While OAuth 2.0 allows scopes to be optional (i.e. omitted), it seems that the implication of using scopes in a `securedBy` is that they be _required_ for the given resource and method **if they've been specified**. The description here of securedBy/SecuritySchemes for OAuth 2.0 is unclear about whether an operation should be permitted if a listed securedBy scope is not present. This appears to have snuck into the current release of APIkit in that one now must provide the complete list of all possible scopes in the securitySchemes definition before it will allow any subset of them to  in an overriding resource securedBy and yet APIkit's implementation makes them optional at the method:resource level. This is confusing at best.

There's no MuleSoft official API Manager policy available at the current time to actually do any OAuth 2.0 scope enforcement that tracks what's defined in the RAML API definition; the available policy ignores the RAML and uses configuration provided separately. One would hope that the RAML would be the source of truth for this.

By way of comparison, [OpenAPI 3.0 Security Requirements Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-requirement-object) appears to more clearly state that (my highlighting): 

> Each name MUST correspond to a security scheme which is declared in the Security Schemes under the Components Object. If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names **required** for the execution....

(I understand I am somewhat conflating the RAML 1.0 spec and MuleSoft's _reference_ implementation, but, it is the only implementation out there that is widely used.)

**Comment by sichvoge** [comment]
Thanks @n2ygk. I will look into your two issues around that topic.

As for the MuleSoft platform, it's not a reference implementation and there isn't anything that we can control on our side as well. If you have a specific requirement for the API Manager to work like you described, you should directly get in touch with MuleSoft. 

Sorry about that.

**Comment by sichvoge** [comment]
OK - Looking quickly into your issue - it seems that there is some confusion. In this issue, we decided to make the node `scopes` for an OAuth 2.0 security scheme definition optional. So for example, before the following was not valid:

```
securitySchemes:
  oauth_2_0:
    description: |
      Dropbox supports OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: |
             Used to send a valid OAuth 2 access token. Do not use
             with the "access_token" query string parameter.
          type: string
      queryParameters:
        access_token:
          description: |
             Used to send a valid OAuth 2 access token. Do not use with
             the "Authorization" header.
          type: string
      responses:
        401:
          description: |
              Bad or expired token. This can happen if the user or Dropbox
              revoked or expired an access token. To fix, re-authenticate
              the user.
        403:
          description: |
              Bad OAuth request (wrong consumer key, bad nonce, expired
              timestamp...). Unfortunately, re-authenticating the user won't help here.
    settings:
      authorizationUri: https://www.dropbox.com/1/oauth2/authorize
      accessTokenUri: https://api.dropbox.com/1/oauth2/token
      authorizationGrants: [ authorization_code, implicit, 'urn:ietf:params:oauth:grant-type:saml2-bearer' ]
```

The spec did not allow that `scopes` in `settings` can be omitted.  What we can do is to further clarify that the value of `scopes` is a list of scope names required for the execution as per your suggestion. 

If that's what you are trying to suggest, please create another issue.

**Comment by n2ygk** [comment]
I should have put "reference" in quotes as it is likely one of the most
significant implementations of RAML.

But the key concern which you do address is that each scope, if provided,
is required to be present for the operation to execute. APIkit seems to
have misinterpreted the spec. I'll file a bug with the vendor.

Thanks.

**Comment by n2ygk** [comment]
To clarify the Mulesoft APIkit issue, if I have RAML like the following (no scopes at all under the securitySchemes and then scopes defined in the resource & method securedBy) the APIkit (as of a recent release - 3.7+?) now seems to require all possible scopes to be defined in the initial securitySchemes and then a subset of them in the securedBy. If there are no scopes defined at the top, then it throws errors like this:
```
ERROR WHILE PARSING
Api contains errors.
[error] The 'read' scope is not allowed for the 'oauth_2_0' security scheme. Allowed scopes are: .
[error] The 'write' scope is not allowed for the 'oauth_2_0' security scheme. Allowed scopes are: .
```

Here's the RAML that reproduces that.
```
#%RAML 1.0  
title: apikit-wrong-scopes
version: v1
description: a demo app that demonstrates APIkit's incorrect interpretation Oauth2.0 scopes
baseUri: /{version}
securitySchemes: 
  oauth_2_0: 
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization?:
          description: OAuth 2 access token. Use EITHER this or the access_token, not both.
          type: string
      queryParameters:
        access_token?:
          description: OAuth 2 access token. Use EITHER this or the Authorization header, not both.
          type: string
      responses:
        401:
          description: Bad or expired token.
        403:
          description: Bad OAuth request
    settings:
      authorizationUri: https://oauth.cc.columbia.edu/as/authorization.oauth2
      accessTokenUri: https://oauth.cc.columbia.edu/as/token.oauth2
      authorizationGrants: 
        - authorization_code
# uncomment this and APIkit "works":
#      scopes: [read, write]
/things:
  displayName: Things
  description: some things
  get:
    securedBy: 
      - oauth_2_0: { scopes: [ read ] }
    responses:
      200:
        body:
          application/json:
            example: {"message":"read"}
  post:
    securedBy: 
      - oauth_2_0: { scopes: [ write ] }
    responses:
      200:
        body:
          application/json:
            example: {"message":"write"}
```
This is a recent change to APIkit which, in older versions, required all scopes in a method's securedBy to be present. The UI now offers checkboxes to optionally select them.

@sichvoge This appears to be a misinterpretation of the RAML spec. Do you concur or am I misreading the spec?

**Comment by n2ygk** [comment]
They say the memory is the second thing to go. I forget what the first is.

I had already submitted support case 00174600 to MuleSoft on 8/3/17 for this exact issue. It's been accepted as a Defect/ER.
