### ISSUE TITLE
Some OAuth 2.0 APIs use a custom parameter name

### ISSUE THREAD

**Issue by blakeembrey** [raml-org/raml-spec#57]
Currently, it is not possible to programatically override the default OAuth 2.0 access token parameter name. For example, [LinkedIn](https://developer.linkedin.com/documents/authentication) uses `oauth2_access_token` while typically the standard is just `access_token`. Having a way to set the property in the security schema settings would be help immensely.

We should be able to override all parameter names that may change, the `code`, `client id`, `client secret`, etc.

**Comment by usarid** [comment]
LinkedIn's use of a query parameter called `oauth2_access_token` is out of conformance with the spec http://tools.ietf.org/html/rfc6750#section-2.3 which, in turn, is the only registered authorization token type for OAuth 2.0. That is, they were not conforming to the OAuth spec. They do seem to conform to it now, accepting a properly-formatted bearer token in an `Authorization` header: https://developer.linkedin.com/docs/oauth2 . 

It feels like we should not go out of our way to provide a standardized mechanism to compensate for non-conforming usage of standards like this. However, you can use an `x-...` security scheme, i.e. RAML's extensibility mechanism for authentication schemes, if you don't want to conform to one of the built-in schemes, and describe it as you wish. It's unlikely RAML processors will always be able to understand such specs and authenticate, but some might.

Note that OAuth2 does have prodigious extensibility mechanisms that seem hard to capture in RAML in a standard, automatable way. Instead, we advocate the development of annotation types, captured in libraries, that describe extensions or variants that are useful. If such libraries become truly useful and broadly-adopted, we could reconsider including them in a future RAML standard.
