### ISSUE TITLE
Basic Information / URI Parameters section should be Basic Information / Base URI Parameters

### ISSUE THREAD

**Issue by eliaslevy** [raml-org/raml-spec#61]
The Basic Information / URI Parameters section incorrectly discusses a top level `uriParameters` property.  This should be a discussion of the top-level `baseUriParameters` property.  To my knowledge there is no top-level `uriParamters` property.

The discussion of the property, as well as the example RAML, are incorrect.

**Comment by sichvoge** [comment]
Seems thats been fixed. thanks!
