### ISSUE TITLE
Best ways to convert RAML Type into Schema draft 4 json format

### ISSUE THREAD

**Issue by rankun203** [raml-org/raml-spec#618]
Since RAML 1.0 now utilize types as its schema definition language, I've been enjoying work with it. Now we want to convert those schema into [Schema draft 4](http://json-schema.org/) json format for later validation directly in our program. This connection would also push us to update the RAML API doc frequently. 

I haven't found any good idea how to do it, any suggestions?

**RAML version:** 1.0
**Schema version:** [Schema draft 4](http://json-schema.org/)
**\* Schema Validator:** [epoberezkin/ajv](https://github.com/epoberezkin/ajv)

**Comment by sichvoge** [comment]
Have you tried https://github.com/raml-org/ramldt2jsonschema
