### ISSUE TITLE
raml-jaxrs-maven-plugin 1.3.4

### ISSUE THREAD

**Issue by paulprashant1510** [raml-org/raml-spec#619]
Hi,  
I am using raml 1.0, I want to generate resources using raml-jaxrs-maven-plugin 1.3.4.
Can someone please tell me is this possible because I am getting multiple errors saying "Error Unknown Key:" for attributes like description, traits,  type.

**Comment by sichvoge** [comment]
Hi @paulprashant1510, you might want to ask that question inside the [raml-for-jaxrs](https://github.com/mulesoft/raml-for-jax-rs) repository.

Short answer, 1.3.4 probably does not support RAML 1.0. There is a [branch](https://github.com/mulesoft-labs/raml-for-jax-rs/tree/release/2.0.0) with that which is currently being tested to collect feedback before it gets merged into the master branch.

**Comment by paulprashant1510** [comment]
Thanks @sichvoge for sharing your input on this.
