### ISSUE TITLE
Validate links in markdown

### ISSUE THREAD

**Issue by MikeRalphson** [raml-org/raml-spec#636]
The changes in #622, #623, #624 and #625 were spotted by a tool called [mdv](https://github.com/mermade/mdv) which runs as part of a CI step in both the [OpenAPI](https://github.com/OAI/openapi-specification) and [AsyncAPI](https://github.com/asyncapi/asyncapi) repositories.

Happy to raise a PR to add it to this repository if that would be accepted - I note that this repository is currently very minimalist in nature, so understand if it would be regarded as noise or bloat.

**Comment by sichvoge** [comment]
I think it is a good idea. It would save time looking for it and reduces the probability of broken links in general

QQ: Where would you add mdv?

**Comment by MikeRalphson** [comment]
> QQ: Where would you add mdv?

As per the [AsyncAPI repository](https://github.com/asyncapi/asyncapi) and [this commit](https://github.com/asyncapi/asyncapi/pull/6/commits/90d8895c24e926814f52f66db03c1dc7add16547), this would involve adding:

* `.travis.yml` -to define the CI step, if Travis is an acceptable CI provider (it is the one I'm most familiar with) - alternatives might include Circle CI.
* `package.json` -to declare the dependency on `mdv` - it would also allow publishing of the spec as an `npm` package in the future if so desired

and modifiying:

* `.gitignore` - to prevent `node_modules` directory etc accidentally being committed

`mdv` would then run on each branch push and PR change once Travis was enabled for the repository by a committer.

**Comment by sichvoge** [comment]
Sounds good. You want to go ahead and send a PR? I will setup travis

**Comment by sichvoge** [comment]
Done! Sorry that it took me so long :)

**Comment by sichvoge** [comment]
@MikeRalphson you are invited to add RAML to the list that runs on mdv now ;)

**Comment by sichvoge** [comment]
@MikeRalphson i have run the travis which executes mdv, but there are still broken links that did not get reported. any ideas why that could happen?

**Comment by MikeRalphson** [comment]
Are they external links? Do you have an example?

**Comment by sichvoge** [comment]
Have a look at #639.

**Comment by MikeRalphson** [comment]
Added new error case in mdv v1.0.7 - technically this was defining an external link, but I think in most cases links like this are going to be errors. Will submit a PR to fix #639 which was the only instance.
