### ISSUE TITLE
Provide a reference to the ECMA Script regular expression specification

### ISSUE THREAD

**Issue by katmatt** [raml-org/raml-spec#647]
**Theme** Improve interoperability

**Description**

As far as I could investigate, the regular expressions used in the RAML facets must comply to the [ECMA-216](https://www.ecma-international.org/ecma-262/5.1/#sec-15.10.1) specification. If this is the case, it would be great to add a reference to the RAML specification. 

This would improve the precision of the specification and would make it easier to write a compliant implementation.

**Comment by sichvoge** [comment]
I think that looks like a duplicate for #577. Can you confirm?

**Comment by katmatt** [comment]
Yes, this issue is a duplicate of #577. I did a search for issues with `regex` and that's why I didn't find #577

**Comment by sichvoge** [comment]
OK, I'll close this then!

**Comment by sichvoge** [comment]
Duplicate of #577
