### ISSUE TITLE
Multiple values of type file

### ISSUE THREAD

**Issue by gromdron** [raml-org/raml-spec#649]
Documenting API in RAML and I can not understand: there is a resource in which you can pass parameters "image" and "video" (multipart).
How to specify that you can load the 'image' without 'video', 'video' without 'image, 'image' and 'video'.
But nothing cannot be downloaded (that is, something must be loaded)

**Comment by sichvoge** [comment]
what about asking your question on our [forum](forums.raml.org)? Maybe you get more people to help you there.
