### ISSUE TITLE
Is there an alternative for patternProperties in 1.0?

### ISSUE THREAD

**Issue by azaslavsky** [raml-org/raml-spec#657]
I've noticed that the equivalent of JSON Schema's [patternProperties](https://spacetelescope.github.io/understanding-json-schema/reference/object.html#pattern-properties) was removed in 1.0.  Is there any way to describe a collection object where ids of a certain type are the key, and a type is always the value?

For example, in [JSON Schema draft-06](http://json-schema.org/draft-06/json-schema-migration-faq.html), I could do the following:

```javascript
{
	title: "ImageCollection"
	description: "A collection object containing images as the values, and image ids as the keys"
	type: "object"
	patternProperties: {
		"[\\\\s\\\\S]*": {$ref: "#/schemas/image"}
	}
	propertyNames: {$ref: "#/schemas/image/definitions/id"}
}
```

Is it possible to replicate this design with RAML 1.0 types?

**Comment by freddrake** [comment]
Yes, it can be done using regular expressions as keys under ``properties:``.  See:

> https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#additional-properties

**Comment by azaslavsky** [comment]
Thanks, much appreciated!
