### ISSUE TITLE
Is there a way to specify request-response pairs?

### ISSUE THREAD

**Issue by Fuco1** [raml-org/raml-spec#660]
I have been looking around and I can't find any way to link a specific request example to a response example.  This seems like a very fundamental feature to me as it allows building automated test suites, mock servers and all sorts of interesting tools.  So I am rather surprised that this is seemingly impossible.

For example, when one endpoint has 3 or 4 return codes it would be useful to have a request example which produces each of those outcomes.  Is this somehow possible?

Thanks!

**Comment by sichvoge** [comment]
That is not possible with what's written in today's spec. It's also the first time I hear about that, specifically.

Nevertheless, annotations could provide you with that option regardless of the constraints in the spec. Tooling could then use it to generate more advanced mocking or test suites, indeed.
