### ISSUE TITLE
Setting an array of Types as a response body results in "RAML had no response information for application/json"

### ISSUE THREAD

**Issue by bromeostasis** [raml-org/raml-spec#669]
I've spent a few hours on what I thought should be a very simple part of RAML, but have had absolutely no success trying to figure it out. Here's what I have:

```
#%RAML 1.0
title: window
baseUri: test.test.com
version: v1

types: 
  ActionType:
    properties: 
      id:
        type: integer
        example: 1
      name:
        type: string
        example: "message"

/actiontypes:
  get:
    responses: 
      200:
        body: 
          application/json:
            type: ActionType[]
```

Using this, I was hoping to generate a realistic mock API which I could call and interact with. I'm using [apidesigner](https://anypoint.mulesoft.com/designcenter) to achieve this.

**Expected**

I'd expect the endpoint to simply return a result with an array of length one with my example parameters in it. 

```
[
    {
        "id": 1,
        "name": "message"
    }
],
```

If I just set `type: ActionType`, it is perfectly capable of returning my example `ActionType` in the JSON format I'd expect.

**Actual**

I keep getting the following:

```
{
"message": "RAML had no response information for application/json"
}
```

I have yet to find a way around this. I really don't want to have to copy a bunch of example data to support both singular and array-based responses, but that seems like my only option at this point. Any help is appreciated, and please point me somewhere else if I'm not reporting this in the right place!

**Comment by jstoiko** [comment]
@bromeostasis: apologies for the late reply. 

Your example is valid RAML. I suggest you file an issue in the [API Designer repository](https://github.com/mulesoft/api-designer/issues).
