### ISSUE TITLE
How to represent a java Map in RAML 1.0

### ISSUE THREAD

**Issue by yprajapati-mob** [raml-org/raml-spec#676]
I have raml schema which contains ` "javaType": "java.util.Map<String, java.util.List<Employee>>"`

I have separate schema (employee.schema) available which represent class Employee.

But as i have not used employee.schema in raml so it is not generating class Employee and throws an Error while converting RAML to Java.

```
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "description": "Desc",
  "properties": {
    "employeeGroups": {
      "type": "object",
      "javaType": "java.util.Map<String, java.util.List<Employee>>"
    }
  },
  "additionalProperties": false
}
```
Can anybody share comments how to represent "javaType": "java.util.Map<String, java.util.List<Employee>>" in RAML ?

**Comment by jstoiko** [comment]
> while converting RAML to Java
which tool are you using? This doesn’t seem to be a RAML specific issue. Have you considered creating an issue on the tool’s repo?
