### ISSUE TITLE
Get the result based on the input query parameters

### ISSUE THREAD

**Issue by RajezMariner** [raml-org/raml-spec#681]
Hi team,

I have attached the stackover flow url posted by me. Could you please check this and help me on this.

https://stackoverflow.com/questions/51282416/how-to-send-different-raml-response-with-different-input-query-parameters.

Thanks,
Rajesh

**Comment by RajezMariner** [comment]
Basically, I want to retrieve the output based on the input parameter. Here my input parameter should be flightId. If I give the flight id="F001", I should the result only of the data present with flight id as "F001" but not the other flight id`s. but I am getting all the result. Not sure where I am missing the validations.

**Comment by jstoiko** [comment]
@RajezMariner: I see you've been answered. Closing this since it is not RAML Spec specific but rather specific to the mocking service you are using. Feel free to re-open if you believe otherwise.
