### ISSUE TITLE
Service Discovery Support ?

### ISSUE THREAD

**Issue by GuangmingLuo** [raml-org/raml-spec#690]
Hi,

Within the client-side code generated by RAML, user has to specify the baseUrl and this baseUrl must be IP+PORT, because there is "builder.build". In this case, we can't set this baseUrl to a application name, which can be used by service discovery. 
RestTemplate used in the code is perfect for service discovery. Why doesn't the code support that ? Can this feature be added ?

I am looking forward to your reply. Thanks.

BR

**Comment by jstoiko** [comment]
@GuangmingLuo: it seems like you reached-out to the wrong project. This repository is for the RAML Spec, your question seems related to a specific tool, and if I had to guess from what you described, I would say [`phoenixnap/springmvc-raml-plugin`](https://github.com/phoenixnap/springmvc-raml-plugin). Am I right? If so, you might want to post your issue there.

**Comment by GuangmingLuo** [comment]
Yes, you are right. Sorry for reaching out to the wrong project.
