### ISSUE TITLE
How to specify a map type property in RAML (example attribute in response body) which can hold any number of key-values

### ISSUE THREAD

**Issue by vickynrj** [raml-org/raml-spec#701]
Hi,
I am novice to RAML, try to write specification for an api. I am having issue in designing response body for an object which contains a property (Map type collection) to hold any number of keys and values. Please help me. In attached picture, there is property “collections” inside “adhocMetaData” object. This “collections” property may get any number of key-value pairs on different requests. How can define this propery while writting responsebody example in raml. Somebody please help me
![jsonobject](https://user-images.githubusercontent.com/45943940/51323240-a015b980-1a8d-11e9-8d86-474aa01d9c24.PNG)

**Comment by jstoiko** [comment]
Closing. Duplicate from https://forum.raml.org/t/how-to-define-a-map-type-property-wich-may-contain-any-number-of-key-values/2383. Please 🙏 only post once.

**Comment by vickynrj** [comment]
Hi Jonathan,

   As my question has been considered duplicate, It will be great help if
you provide me relavent post url which is having solution to my problem.
Thanks.
