### ISSUE TITLE
Displaying description of properties contained in json schema

### ISSUE THREAD

**Issue by vickynrj** [raml-org/raml-spec#703]
Hi @jstoiko I am using api-console 3.0.31 for documentation. When writing get/post requests, I am referring json schema for showing request and response examples. Now my problem is, I want to display description of every attributes defined in json schema. For example in this api https://mulesoft.github.io/api-console/#docs/method/#2971

Every attribute's description is displayed below body example. It makes easy to user to get info about what a json request or response contains. 

I am sharing my raml file. also attached screenshot which displays information of all attributes contained in json resquest/response
![googledrive](https://user-images.githubusercontent.com/45943940/52051658-3364e980-257a-11e9-8aaf-32cebe78e2ad.PNG)

**Comment by vickynrj** [comment]
Below is my raml file content...

#%RAML 1.0
title: Email
version: v1.0
baseUri: http://localhost:8080/LDservices
protocols:  [HTTP, HTTPS]  
securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication
   
     
mediaType: application/json
schemas:
  -create-report: !include /schemas/create-report-req.json
  -create-report-res: !include /schemas/create-report-res.json
  -loadReportReq : !include /schemas/loadReport-req.json
  -loadReportRes : !include /schemas/loadReport-res.json
  -saveReportReq : !include /schemas/saveReport-req.json
  -saveReportRes : !include /schemas/saveReport-res.json
  -workspaceInfo : !include /schemas/getWorkspaceInfo-res.json
  -deleteReport:  !include /schemas/deleteReport-req.json
  -success:  !include /schemas/success.json

/reports:
    displayName: Report
    /create:
      displayName: Create Report      
      post:
        description: Service to create a report.
        securedBy: [basic]
        body:
          application/json:
            schema: create-report
            example: !include /schemas/create-report-req.json
        responses:
          200:
           body:
             application/json:
               schema: create-report-res
               example: !include /schemas/create-report-res.json

    /loadReport/{reportId}: 
      displayName: Load Report  
      uriParameters:
        reportId:
          displayName: Report ID
          type: string
          example: a4c42d6508670546d426cbe5bb02bfda
          required: true
      post:
        description: Service to load a report for given reportID
        securedBy: [basic]
        body:
          application/json:
            schema: loadReportReq
            example: !include /schemas/loadReport-req.json
        responses:
          200:
            body:
              application/json:
                schema: loadReportRes
                example: !include /schemas/loadReport-res.json

    /save:       
      displayName: Save Report  
      post:
        description: Service to save report
        securedBy: [basic]
        body:
          application/json:
            schema: saveReportReq
            example: !include /schemas/saveReport-req.json
        responses:
          200:
           body:
             application/json:
               schema: saveReportRes
               example: !include /schemas/saveReport-res.json

    /deleteReport:   
      displayName: Delete Report
      post:
        description: Service to delete the Report
        securedBy: [basic]
        body:
          application/json:
            schema: deleteReport
            example: !include /schemas/deleteReport-req.json
        responses:
          200:
           body:
             application/json:
               schema: success
               example: !include /schemas/success.json
                            

    /getWorkspaceInfo/{workspaceId}: 
      displayName: Workplace Info
      uriParameters:
         workspaceId:
            displayName: Workspace Id
            type : string
            required : true
            example: 26a0f27e7d25e1e4:57e00811:1685bca0f2f:-71ab
      get:
        description: Use this service to get workspace info
        securedBy: [basic]
        responses:
          200:
           body:
             application/json:
               schema: workspaceInfo
               example: !include /schemas/getWorkspaceInfo-res.json


documentation:
  - title: Introduction
    content: LD service API is used for processing large size of data to produce well analyzed, customized Reports based on various measures.

**Comment by vickynrj** [comment]
@antoniogarrote @jstoiko @jlouvel @muratcorlu  Guys, please provide your valuable suggestions on above issue. Thanks!

**Comment by jstoiko** [comment]
This is an issue related to API Console, not RAML per sé. I'll close this and suggest you file an issue in the [API Console Github repository](https://github.com/mulesoft/api-console/issues).
