### ISSUE TITLE
How to combine  multiple ramls to generate master raml

### ISSUE THREAD

**Issue by vickynrj** [raml-org/raml-spec#705]
Hi,

Based on the requirement, I have two raml specifications:
1- order_api.raml  (http://api.com/orders/*)
2- sales_api.raml  (http://api.com/sales/*)

Can I combine both RAML specification to produce single raml for example api.raml
In future I may have multiple api specification raml for different functionalities.
So Is there any way to combine all specification raml files to produce master raml file. Please help.

**Comment by jstoiko** [comment]
You can certainly do that using a parser/tool that can produce ASTs from RAML (or even straight YAML) files. I invite you to look into [`webapi-parser`](https://github.com/raml-org/webapi-parser). That being said, this is not a RAML issue as it pertain to tooling so I'll close this.
