### ISSUE TITLE
Clarify nilable property alternative syntax

### ISSUE THREAD

**Issue by jstoiko** [raml-org/raml-spec#708]
The only place where this alternative syntax of nilable property is mentioned is in a comment on the last example of the [Nil Type](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#nil-type). See also #665.

### Proposed clarification
- at the end of the first paragraph of the ["Nil Type"](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#nil-type) section, add a sentence about "nilable". e.g. 

> Using the type `nil` in a union of one or multiple types, makes a type definition nilable, meaning that its value is allowed to be `null`. When such union is composed of only one type in addition to `| nil`, a trailing question mark `?` in lieu of such union is equivalent. 

- remove the `equivalent to comment: string?` from that example
- add a sentence at the end of that section explaining the equivalent syntax along with an example
- make sure this syntax can only be applied to scalar types and type references, i.e. forbidden in type expressions
- address corner-case of user-defined type with trailing question mark (see comment below)

**Comment by jstoiko** [comment]
We also need to cover the corner-case of a type definition whose name contains a trailing question mark, e.g.
```raml
types:
  MyTypeWithTrailing?: number
  MyNullableType: MyTypeWithTrailing? | nil
  MyAlternativeSyntaxForNullableType: MyTypeWithTrailing??
```

**Comment by postatum** [comment]
> We also need to cover the corner-case of a type definition whose name contains a trailing question mark, e.g.

Done.
