### ISSUE TITLE
Clarify formatting of examples

### ISSUE THREAD

**Issue by jstoiko** [raml-org/raml-spec#709]
[As it stands](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#defining-examples-in-raml), it is not clear how examples may be formatted (I.e. xml, json, yaml, <anything else>?) and whether those example representations should be validated when `strict: true` (default) and the processor faces an example format it does not understand. I.e. does it mean that RAML processors must parse and validate ANY format?

### Proposed clarification
- rewrite description of `strict?` to mention, like `schema?` for [Type Declarations](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#type-declarations) that, in addition to the default YAML format, JSON and XML representations of examples are also supported.
- add that any other format is not guaranteed to be validated, that it is up to the processor to support
- add a note explaining that the format of examples is independant from the format of the corresponding type instance. This means that, for example, a JSON or YAML-formatted example may be used to represent an XML (`application/xml` content-type) payload or vice-versa.

**Comment by postatum** [comment]
I think `strict` description should be updated as well. It says

> Validates the example against any type declaration (the default), or not. Set this to false avoid validation.

The `any type declaration` seems confusing to me.
