### ISSUE TITLE
Clarify how to infer/determine the default type for ALL built-in types

### ISSUE THREAD

**Issue by jstoiko** [raml-org/raml-spec#710]
In the [`Determine Default Types`](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#determine-default-types) section, a number of rules are enumerated to help infer a type without having to specify the `type` facet. 

The first rule mentions how setting a facet that is unique to a given type removes the need to specify the `type` facet. The issue is that it only specifies `properties` as inferring `type: object`. This was clearly an oversight when writing the Spec as there are other types that have facets unique to them such as `fileTypes` for `type: file` and `items` for `type: array`.

### Proposed clarification:
- change the first rule from:
> If, and only if, a type declaration contains a properties facet, then the default type is object

to:
> If, and only if, a type declaration contains a facet that is unique to that type, then the default type is that type
- adapt subsequent rules referring to the first one
- make it clear that the `type: object`/`properties` in that first rule is only an example

**Comment by postatum** [comment]
It looks like it's impossible to determine default type for boolean, date and nil as they either don't have unique facets or have no facets at all.

**Comment by jstoiko** [comment]
You're right. Doesn't seem to contradict the proposed clarification above though, does it?

**Comment by postatum** [comment]
> You're right. Doesn't seem to contradict the proposed clarification above though, does it?

It doesn't.
