### ISSUE TITLE
Clarify how to resolve `!include`s and libraries inside Overlay and Extension fragments

### ISSUE THREAD

**Issue by jstoiko** [raml-org/raml-spec#719]
In the context of RAML Overlay and Extension fragments, it is not clear whether the root is the overlay/extension fragment itself or the RAML file that it extends. This matters when an overlay or extension fragment is not located in the same folder as the RAML file that it extends.

### Proposed changes
At the end of the following paragraph:
> The remainder of an overlay or extension document follows the same rules as a RAML API definition, but with certain restrictions in case of an overlay.

(see ["Overlays and Extensions"](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#overlays-and-extensions))

Add the following clarification: `The resolution of any relative or absolute paths in an overlay or extension document such as any !include tags or libraries MUST be done relatively to such overlay or extension document.`

**Comment by postatum** [comment]
Why also `absolute paths`? Aren't absolute path already resolved relative to the root of filesystem/some http source?

**Comment by jstoiko** [comment]
Root in RAML = path of the RAML API root document. Any resolution is relative to that root EXCEPT for the resolutions of paths defined inside Overlay/Extension documents.
