### ISSUE TITLE
Rename baseUri to baseUrl

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#72]
The root property should be called baseUrl, because it really is the locator for the hosted API.

Also, it currently says:

> The use of the baseUri field is OPTIONAL to allow describing APIs that have not yet been implemented. After the API is implemented (even a mock implementation) and can be accessed at a service endpoint, the API definition MUST contain a baseUri property.

It should always be optional.

> The use of the baseUrl field is OPTIONAL.

**Comment by jptalton** [comment]
for those of us using baseUri to specify a urn, this change isn't needed, and would make the raml document less flexible (and our current code incorrect)

sticking with uri (as the superset of url and urn) provides the flexibility for implementers at the slight cost of a bit of confusion in the case where someone uses url (and scratches there head asking why is this called uri, which could have an actual positive effect if this drives them to check the uri spec :) )

why use urn:
several reason, including the mentioned api draft time uncertainty and others...

more specifically however, it can also be used when the url is not fully known until deploy/runtime.  at which time the urn is converted into a url.

urn://company/api/foo/ gets mapped to https://api-host,company.com/some-scope/foo/

the deploy/runtime is able to pick appropriate scheme, hostname etc 

this level of abstraction keeps raml authors hands clean from actual implementation details



if there is a better approach to this, or if I have missed some details that invalidate the use case etc please let me know

thanks

**Comment by usarid** [comment]
Fascinating. I've not personally seen the baseUri being used as a urn advantageously as you suggest, but would love to, and understand *in  practice* how you can achieve the decoupling that I agree is good. Can you share examples and maybe a bunch more on how you're doing it in the real world?

**Comment by dfeist** [comment]
I agree with @jptalton I don't think a baseURL belongs in RAML definition at all, for a lot of reason which I can detail if people are interested.  Also I think it's a great idea to for RAML's to have a URI/URN.

In terms of how we tackle this, I would suggest removing baseUri and uriParameters completely and then tackling the URN story separately ensuring we give it some real thought. One of the things to give some thought is URN vs. URI, URI allowing us to suggest that by convention the URI is the location of the RAML for example (as is common with XML namespaces).

**Comment by sichvoge** [comment]
I do agree for the `baseUri`, but not for the `uriParameters` as you could have these parameters defined inside a resource definition as well.

**Comment by usarid** [comment]
I'm not really seeing what's wrong with keeping things as is, allowing you to use or omit baseUri, parametrize it as you wish, use it as a URL or not, and perhaps add annotations to inform processors of handling. You could also just point it to a registry and let an http redirect guide you to the location of the endpoint.






On Fri, Oct 9, 2015 at 6:34 AM -0700, "Christian Vogel" <notifications@github.com> wrote:












I do agree for the baseUri, but not for the uriParameters as you could have these parameters defined inside a resource definition as well.

**Comment by sichvoge** [comment]
I think it's just the concept of having it in there. I am thinking of use cases where having a `baseUri` could be a bad thing such as multi environments like test, dev, etc. @usarid what's your point to have it in there? I've heard a lot about why not, so I would love to hear more about why it should stay as it is.

**Comment by usarid** [comment]
Because in a huge number of usecases, using it as a baseUrl works great. And leaving it open to more general URI usecases looks promising too.






On Fri, Oct 9, 2015 at 7:17 AM -0700, "Christian Vogel" <notifications@github.com> wrote:












I think it's just the concept of having it in there. I am thinking of use cases where having a baseUri could be a bad thing such as multi environments like test, dev, etc. @usarid what's your point to have it in there? I've heard a lot about why not, so I would love to hear more about why it should stay as it is.

**Comment by lowema** [comment]
I've been thinking long and hard about this, and have come to the conclusion that this should be a URI and not a URL.
The thing about a baser URL is that it can vary from implementation environment to environment, and would never reflect one source of truth. It may even be that for some implementations of an API, a certain partner would be given a different URL to access their implementation of it, such as in cases where some "ring fenced" hardware and capacity is installed, which happens a fair amount, despite what people say.
We need to decide, once and for all, whether RAML itself is a descriptive definition of the API or a descriptive definition of an instance of an API in an environment. For me, it is the former, as i would like to see the implementation parameters separate to the API definition.
Given the architectural style we are about to adopt, this will cause us problems if RAMLs come in with URLs to connect to, as we are designing standard components with APIs that would be used in different services on different URL endpoints.
As i say, we need to decide if we are designing an API definition language or we are spreading out to cover implementation as well. If we are going to cover implementation then we need to think long and hard about all of the deployment use cases, and to cover them all in the language.
I believe that this is where WSDL went wrong, and we'd hate to make that same mistake, right ?

**Comment by lowema** [comment]
Whilst thinking about this more, while i was typing to be honest, was the machine readable aspect of RAML. If there is any ambiguity in the use of a field or tag then it makes the machine readability a joke.
We have to mandate field use, and contain it to a single purpose. Machines are crap at making decisions in a subtle context, unless you have a machine the size of Watson or Deep Blue.

I will re-iterate, be good at one thing. Make sure each thing has a single purpose. Make sure it's good enough and no more. Mandate use. Be pro-active in policing it.

It is the price we have to pay to make a solid and reliable standard that can be used in machine and human readable forms.

**Comment by usarid** [comment]
I certainly hear the concerns, and I share them. People are using RAML for
instances of API implementations and for the pure interface itself. We've
clarified in RAML 1.0 that the baseUri is entirely optional, so you can use
a RAML file for both. I'm certainly hoping that RAML is very useful for the
interface itself. I also know it's adding a lot of value for
implementations, whether in a mocking context pre-implementation or when
it's actually published, and a lot of tools make use of that. So at this
point we'll keep the baseUri in, and not change it to baseUrl to allow a
broader set of uses. And I don't see us embedding into the spec a whole
bunch of SDLC functionality, so no worries about going down that road.

**Comment by sichvoge** [comment]
Why are we not pushing annotations and overlays for that kind of "configuration"? Therefore we would avoid to have implementation and design constructs in the spec

**Comment by usarid** [comment]
In RAML 1.0 you can use extensions to, among other things, introduce or
override the `baseUri` property in exactly this way. I don't want to cut
off the possibility of have a `baseUri` as the URL of the API endpoint in
the RAML spec itself as a lot of people find it very useful, but if you
choose to use the RAML spec itself for the pure interface, then the
location of the implementation can be specified in an extension file, which
references the original API and extends it with a `baseUri`.

You can also choose to create your own annotations to better describe the
location of the API, but for now it will be non-standard, so until we
figure out a better way to do it than the `baseUri` mechanism (and as Mark
Lowe points out, there's more to this than meets the eye), different tools
may not know what to do with that -- and that's fine for now. Annotations
are also a way to inform the next version of the spec ;-)

Note that overlays would only be useful here if you chose to do it via
custom annotations as they cannot change the functional parts of the spec
such as `baseUri`. We want overlays to always be "safe" that way.
