### ISSUE TITLE
Issue with second "Introduction" link in RAML 1.0 table of contents

### ISSUE THREAD

**Issue by Pluto71** [raml-org/raml-spec#725]
There are two different "Introduction" links in the table of contents, one for the main intro and another for Datatypes, but they both link to the same spot.

**Comment by jstoiko** [comment]
Thanks for pointing it out @Pluto71. The second link should indeed point to https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#introduction-1. 

Will add it the list of small fixes we're currently including as part of the RAML [1.0.1](https://github.com/raml-org/raml-spec/milestone/7) patch (see branch `misc_clarifications`).
