### ISSUE TITLE
Clarify whether resource type and trait parameters can be used in modularization

### ISSUE THREAD

**Issue by jstoiko** [raml-org/raml-spec#730]
The ["Resource Type and Trait Parameters" section](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#resource-type-and-trait-parameters) contains a restriction on the use of parameters but only includes are mentioned. This restriction should apply to all types of modularization.

### Proposed Change

Rewrite:
> Parameters cannot be used within an !include tag specification of the include file location.

to read:
> Parameters cannot be used within any file location used in the context of [modularization](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#modularization), that is any file location defined in the `!include` tag or as value of any of the `uses` and `extends` nodes.

**Comment by postatum** [comment]
I may be missing something, but I think it's not possible to use "resource type and trait parameters" in "uses" and "extends" as both of these must be defined at the root of the document, according to spec.
