### ISSUE TITLE
Skip a Perticular API documentation in RAML documentation

### ISSUE THREAD

**Issue by sampadc** [raml-org/raml-spec#731]
Is it Possible in RAML to skip a particular REST API Documentation in Spring Boot or it's not possible in RAML.

**Comment by jstoiko** [comment]
I think this would be a question for whatever (Spring Boot) tool you are using along with your RAML definitions. 

As far as RAML is concerned, "skipping" can be expressed in different ways. That I can think of, using annotations would be one way and using overlays to add or remove specific "documentation" parts would be another.
