### ISSUE TITLE
Examples validation

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#75]
In order to improve the quality of generated RAML specifications, we should add to the spec some wording like the following:

> RAML processors MUST validate that examples for named parameters or responses are valid according to the schema, regular expressions or type.

**Comment by sichvoge** [comment]
Should be required for spec IMO. +1

**Comment by sichvoge** [comment]
Looking at this again I think, this is tooling IMHO. It shouldn't be mandated by the spec. @usarid shall we close that?

**Comment by freddrake** [comment]
This sounds like tooling to me.  A development team can choose to be careful, or not.  If developers really want to do something ridiculous, it's not the job of the spec to stop them.  It is the job of the spec to make it possible for tool builders and developers to agree on what a valid API definition means.

**Comment by usarid** [comment]
In RAML 1.0 you can specify, when you have multiple (named) examples, whether each should be `strict` or not, which means should it be validated or not. By default it is validated. I think it correlates with whether you think examples are part of the machine-readable rigorous spec or if they're just hints for humans.
