### ISSUE TITLE
Make a note that all markdown is GFM

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#80]
RAML MUST be prescriptive and say which version of Markdown is valid in the documentation.

**Comment by geewrites** [comment]
To avoid religious wars, I advocate including in the RAML 1.0 spec a formal way to identify the markdown specification the API prefers. Some prefer Github-flavored Makdown, others prefer Vim-flavored Markdown, and still others can't live without CommonMark. 

If it is necessary to choose just one, I hope CommonMark will be seriously considered. When combined with the Markdown DITA plugin, CommonMark can be consumed by the DITA Open Toolkit. through which Markdown can be transformed into a variety of delivery formats.
