### ISSUE TITLE
Remove prescription of JSON schema versions

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#81]
RAML spec says that JSON schemas MUST be draft v 0.3. We should remove the restriction. Since all JSON schemas have the version embedded, we should allow RAML processors, list which versions of JSON schema they support.

**Comment by JonathanMontane** [comment]
> Since all JSON schemas have the version embedded

This is not true. It is recommended to have have the `$schema` field at the root of your schema, but it is in no way a requirement. (`{}` is a valid JSON schema)
