### ISSUE TITLE
Clarify named parameters authority

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#86]
There is some ambiguity as to who is responsible for filling in the default values for named parameters.

>For URI parameters, RAML clients MUST fill the default value into the URI before make requests to the API.
For Headers, Form Parameters, Query String Parameters, if the parameter is flagged as not `required` and having a `default` value, the API must act as if the API client has sent the parameter with the value being the value in the `default` property.

**Comment by sichvoge** [comment]
The current 1.0 spec adds more clarity around the default values. So I think this is obsolete now. @usarid would you agree?

**Comment by aldonline** [comment]
Will be clarified in the RAML1.0 spec. The following additions should fix this:

----

For URI parameters, RAML clients MUST fill the default value into the URI before make requests to the API. 

For Headers, Query String Parameters, if the parameter is flagged as not required and having a default value, **and the request is missing the parameter**, then the API must act as if the API client has sent the parameter with the value being the value in the default property.

**Comment by sichvoge** [comment]
I can't find that somewhere. Is that still needed?
