### ISSUE TITLE
Rename named parameter properties for consistency

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#93]
The spec uses minimum and maximum for parameter validation, but then also uses minLength and maxLength.
RAML 1.0 should standardise on a single naming scheme, it should use the full word.

`minLength` should become `minimumLength`

`maxLength` should become `maximumLength`

**Comment by sichvoge** [comment]
@aldonline @usarid I've seen in the 1.0 draft that we are still using minLength and maxLength, but also minimum and maximum, do you think it makes sense to change that?

**Comment by usarid** [comment]
I think we'll leave it as is.
