### ISSUE TITLE
Remove inline Trait and Resource Type declaration

### ISSUE THREAD

**Issue by nohorbee** [raml-org/raml-spec#98]
RAML 1.0 should not allow the definition of inline resourceTypes in the `type` property of a resource or the definition of traits. This is highly ambiguous.

The highlighted wording should be removed.
> The value of the type attribute MUST be either a) one and only one of the resource type keys (names) included in the resourceTypes declaration, or **b) one and only one resource type definition map**.

**Comment by sichvoge** [comment]
@aldonline @usarid is that even possible now. i agree that we shouldn't allow that as it wouldn't make sense from a re-usability aspect. what do you think?

**Comment by usarid** [comment]
In RAML 1, you can indeed define the value of the `type` property as a schema, e.g. with an `!include`. That's necessary to wrap XML and JSON schema

**Comment by usarid** [comment]
The reason it's in the spec is to allow the following construct:
```
/users:
  type: !include resourceTypes/collection.raml
```
which, like any `!include`, is defined to be equivalent to inlining the contents of `resourceTypes/collection.raml` in the API definition where the `!include` appeared.

**Comment by sichvoge** [comment]
That actually has been considered and agreed to remove. See #321
